#!/bin/bash
#
# Production Monitoring Setup for AITBC Platform
# Configures monitoring, alerting, and observability
#
# This script generates four monitoring scripts and schedules three of them. It does not
# monitor anything itself; run it once on a node to install them.
#

set -euo pipefail

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"; }
success() { echo -e "${GREEN}✅ $1${NC}"; }
warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }

# Not /opt/aitbc/monitoring: that is inside the git checkout the services run from, so
# four generated scripts and three growing logs land there as untracked files. Same
# reason security_hardening.sh stopped generating a checker into the tree (V23-98).
MONITORING_DIR="${AITBC_MONITORING_DIR:-/var/lib/aitbc/monitoring}"

# Every generated script reads this file first, so a node can be retargeted without
# editing generated code. The generator writes a commented template if it is absent.
MONITORING_ENV="${AITBC_MONITORING_ENV:-/etc/aitbc/monitoring.env}"

mkdir -p "$MONITORING_DIR"

# The preamble every generated script starts with. It carries the three things that were
# wrong when these probes were written down as literals:
#
#   * the API URL. It was https://aitbc.bubuit.net/api/v1/health. That name does not
#     resolve from this host (this is aitbc3.aitbc.bubuit.net), and where it does resolve
#     the /v1/ prefix answers 401 from the coordinator's auth middleware, never 200 — so
#     the 200 comparison below could not pass. Both spellings were also written
#     `curl -s ... || echo "000"`, which turns a DNS failure into a recorded status code.
#   * the unit names. "aitbc-coordinator" and "blockchain-node" are not units on any
#     AITBC host; they are aitbc-coordinator-api and aitbc-blockchain-node (V23-98).
#   * where output goes, as above.
#
_preamble() {
    cat << 'PREAMBLE'
# Generated by scripts/monitoring/production_monitoring.sh -- edit that, not this file.
[ -f /etc/aitbc/monitoring.env ] && . /etc/aitbc/monitoring.env

MONITORING_DIR="${AITBC_MONITORING_DIR:-/var/lib/aitbc/monitoring}"
# The coordinator this node runs. Set AITBC_API_HEALTH_URL to "$HUB_URL/api/health" in
# /etc/aitbc/monitoring.env to watch the public edge instead; /api/v1/health is not a
# probe path anywhere -- it 404s locally and 401s through the hub's gateway.
API_HEALTH_URL="${AITBC_API_HEALTH_URL:-http://localhost:8203/health}"
COORDINATOR_UNIT="${AITBC_COORDINATOR_UNIT:-aitbc-coordinator-api}"
BLOCKCHAIN_UNIT="${AITBC_BLOCKCHAIN_UNIT:-aitbc-blockchain-node}"
PREAMBLE
}

# Write the template config, so the operator has somewhere to point the probe.
write_monitoring_env() {
    if [[ -f "$MONITORING_ENV" ]]; then
        log "$MONITORING_ENV exists, leaving it alone"
        return 0
    fi

    mkdir -p "$(dirname "$MONITORING_ENV")"
    cat > "$MONITORING_ENV" << 'EOF'
# Read by every script scripts/monitoring/production_monitoring.sh generates.
# Uncomment and edit to retarget the probes on this node.

# What "the API is up" means here. Defaults to this node's coordinator-api.
# On a hub, the public edge is the more useful target:
#AITBC_API_HEALTH_URL="https://hub.aitbc.bubuit.net/api/health"

# Units to watch. A unit this node does not have is skipped, not alerted.
#AITBC_COORDINATOR_UNIT="aitbc-coordinator-api"
#AITBC_BLOCKCHAIN_UNIT="aitbc-blockchain-node"

# Where the generated scripts write.
#AITBC_MONITORING_DIR="/var/lib/aitbc/monitoring"
EOF
    chmod 644 "$MONITORING_ENV"
    success "Wrote template $MONITORING_ENV"
}

# Add a crontab line unless it is already there. Nothing guarantees this script runs once,
# and every install used to append unconditionally: run it three times and metrics are
# collected three times a minute by three identical jobs.
schedule() {
    local when="$1" command="$2"

    if crontab -l 2>/dev/null | grep -qF -- "$command"; then
        log "Already scheduled: $command"
        return 0
    fi

    # `|| true` because the subshell inherits set -e: on a host with no crontab yet,
    # `crontab -l` exits 1 and the whole generator died there before writing anything.
    (crontab -l 2>/dev/null || true; echo "$when $command") | crontab -
    log "Scheduled ($when): $command"
}

# Setup system metrics collection
setup_system_metrics() {
    log "Setting up system metrics collection..."

    {
        echo '#!/bin/bash'
        echo '# System metrics collection for AITBC platform'
        _preamble
        cat << 'EOF'

METRICS_FILE="$MONITORING_DIR/metrics.log"
TIMESTAMP=$(date -Iseconds)

# System metrics
CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | sed 's/%us,//')
MEM_USAGE=$(free | grep Mem | awk '{printf "%.1f", $3/$2 * 100.0}')
DISK_USAGE=$(df -h / | awk 'NR==2{print $5}' | sed 's/%//')

# Service metrics
COORDINATOR_STATUS=$(systemctl is-active "$COORDINATOR_UNIT" 2>/dev/null || true)
BLOCKCHAIN_STATUS=$(systemctl is-active "$BLOCKCHAIN_UNIT" 2>/dev/null || true)

# API metrics. --max-time so a hung probe cannot outlive its two-minute slot.
#
# `|| VAR=default` rather than `|| echo default`: -w still writes its (zero) value when
# the request fails, so the echo appended a second one and the row read api_status:000000.
API_RESPONSE_TIME=$(curl -s -o /dev/null --max-time 10 -w '%{time_total}' "$API_HEALTH_URL") || API_RESPONSE_TIME="0.000000"
API_STATUS=$(curl -s -o /dev/null --max-time 10 -w '%{http_code}' "$API_HEALTH_URL") || API_STATUS="000"

mkdir -p "$MONITORING_DIR"
echo "$TIMESTAMP,cpu:$CPU_USAGE,memory:$MEM_USAGE,disk:$DISK_USAGE,coordinator:${COORDINATOR_STATUS:-unknown},blockchain:${BLOCKCHAIN_STATUS:-unknown},api_time:$API_RESPONSE_TIME,api_status:$API_STATUS" >> "$METRICS_FILE"

# Keep only last 1000 lines
tail -n 1000 "$METRICS_FILE" > "$METRICS_FILE.tmp" && mv "$METRICS_FILE.tmp" "$METRICS_FILE"
EOF
    } > "$MONITORING_DIR/collect_metrics.sh"

    chmod +x "$MONITORING_DIR/collect_metrics.sh"
    schedule "*/2 * * * *" "$MONITORING_DIR/collect_metrics.sh"

    success "System metrics collection configured"
}

# Setup alerting system
setup_alerting() {
    log "Setting up alerting system..."

    {
        echo '#!/bin/bash'
        echo '# Alert checking for AITBC platform'
        _preamble
        cat << 'EOF'

ALERT_LOG="$MONITORING_DIR/alerts.log"
TIMESTAMP=$(date -Iseconds)
ALERT_TRIGGERED=false

mkdir -p "$MONITORING_DIR"

# Check service status. A unit this host does not have is not a fault: hub, follower and
# shop nodes run different sets, and alerting on the absent ones is an alarm that fires
# forever and teaches the operator to ignore the channel (V23-98).
check_service() {
    local service=$1

    if [[ "$(systemctl is-enabled "$service" 2>/dev/null || true)" == "not-found" ]]; then
        echo "ℹ️  $service is not installed on this host, skipping"
        return 0
    fi

    local status
    status=$(systemctl is-active "$service" 2>/dev/null || echo "failed")

    if [[ "$status" != "active" ]]; then
        echo "$TIMESTAMP,SERVICE,$service is $status" >> "$ALERT_LOG"
        echo "🚨 ALERT: Service $service is $status"
        ALERT_TRIGGERED=true
    fi
}

# Check API health
check_api() {
    local response
    response=$(curl -s -o /dev/null --max-time 10 -w '%{http_code}' "$API_HEALTH_URL") || response="000"

    if [[ "$response" != "200" ]]; then
        echo "$TIMESTAMP,API,$API_HEALTH_URL returned $response" >> "$ALERT_LOG"
        echo "🚨 ALERT: API health check failed (HTTP $response for $API_HEALTH_URL)"
        ALERT_TRIGGERED=true
    fi
}

# Check disk space
check_disk() {
    local usage=$(df / | awk 'NR==2{print $5}' | sed 's/%//')

    if [[ $usage -gt 80 ]]; then
        echo "$TIMESTAMP,DISK,Disk usage is ${usage}%" >> "$ALERT_LOG"
        echo "🚨 ALERT: Disk usage is ${usage}%"
        ALERT_TRIGGERED=true
    fi
}

# Check memory usage
check_memory() {
    local usage=$(free | grep Mem | awk '{printf "%.0f", $3/$2 * 100.0}')

    if [[ $usage -gt 90 ]]; then
        echo "$TIMESTAMP,MEMORY,Memory usage is ${usage}%" >> "$ALERT_LOG"
        echo "🚨 ALERT: Memory usage is ${usage}%"
        ALERT_TRIGGERED=true
    fi
}

# Run checks
check_service "$COORDINATOR_UNIT"
check_service "$BLOCKCHAIN_UNIT"
check_api
check_disk
check_memory

# If no alerts, log all clear
if [[ "$ALERT_TRIGGERED" == "false" ]]; then
    echo "$TIMESTAMP,ALL_CLEAR,All systems operational" >> "$ALERT_LOG"
    exit 0
fi

# Non-zero so cron mails the run that found something, rather than the log being the only
# place an alert exists.
exit 1
EOF
    } > "$MONITORING_DIR/check_alerts.sh"

    chmod +x "$MONITORING_DIR/check_alerts.sh"
    schedule "*/5 * * * *" "$MONITORING_DIR/check_alerts.sh"

    success "Alerting system configured"
}

# Setup performance dashboard
setup_dashboard() {
    log "Setting up performance dashboard..."

    {
        echo '#!/bin/bash'
        echo '# Performance dashboard for AITBC platform'
        _preamble
        cat << 'EOF'

clear 2>/dev/null || true
echo "🔍 AITBC Platform Performance Dashboard"
echo "========================================"
echo "Last Updated: $(date)"
echo ""

# System Status
echo "📊 System Status:"
echo "CPU: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | sed 's/%us,//')% used"
echo "Memory: $(free -h | grep Mem | awk '{print $3"/"$2}')"
echo "Disk: $(df -h / | awk 'NR==2{print $3"/"$2" ("$5")"}')"
echo ""

# Service Status
echo "🔧 Service Status:"
for unit in "$COORDINATOR_UNIT" "$BLOCKCHAIN_UNIT" nginx; do
    if systemctl is-active --quiet "$unit"; then
        echo "✅ $unit: Active"
    elif [[ "$(systemctl is-enabled "$unit" 2>/dev/null || true)" == "not-found" ]]; then
        echo "➖ $unit: not installed here"
    else
        echo "❌ $unit: Inactive"
    fi
done
echo ""

# API Performance
echo "🌐 API Performance:"
API_TIME=$(curl -s -o /dev/null --max-time 10 -w '%{time_total}' "$API_HEALTH_URL") || API_TIME="0.000000"
API_CODE=$(curl -s -o /dev/null --max-time 10 -w '%{http_code}' "$API_HEALTH_URL") || API_CODE="000"
echo "$API_HEALTH_URL: HTTP $API_CODE in ${API_TIME}s"
echo ""

# Recent Alerts (last 10)
echo "🚨 Recent Alerts:"
if [[ -f "$MONITORING_DIR/alerts.log" ]]; then
    tail -n 10 "$MONITORING_DIR/alerts.log" | while IFS=',' read -r timestamp type message; do
        echo "  $timestamp: $message"
    done
else
    echo "  No alerts logged"
fi
echo ""

# Quick Stats
echo "📈 Quick Stats:"
if [[ -f "$MONITORING_DIR/metrics.log" ]]; then
    echo "  Metrics collected: $(wc -l < "$MONITORING_DIR/metrics.log") entries"
    # Every row this log carries is either an alert or ALL_CLEAR, and none of them contain
    # the string "ALERT" -- counting that matched nothing, and grep -c prints 0 and exits
    # 1, so the `|| echo 0` fallback printed a second zero on a line of its own.
    ALERT_COUNT=$(grep -vc "ALL_CLEAR" "$MONITORING_DIR/alerts.log" 2>/dev/null) || ALERT_COUNT=0
    echo "  Alerts triggered: $ALERT_COUNT"
fi

echo ""
echo "Press Ctrl+C to exit, or refresh in 30 seconds..."
sleep 30
exec "$0"
EOF
    } > "$MONITORING_DIR/dashboard.sh"

    chmod +x "$MONITORING_DIR/dashboard.sh"

    success "Performance dashboard created"
}

# Setup log analysis
setup_log_analysis() {
    log "Setting up log analysis..."

    {
        echo '#!/bin/bash'
        echo '# Log analysis for AITBC platform'
        _preamble
        cat << 'EOF'

LOG_DIR="/var/log"
ANALYSIS_FILE="$MONITORING_DIR/log_analysis.txt"
TIMESTAMP=$(date -Iseconds)

mkdir -p "$MONITORING_DIR"
echo "=== Log Analysis - $TIMESTAMP ===" >> "$ANALYSIS_FILE"

# Analyze nginx logs
if [[ -f "$LOG_DIR/nginx/access.log" ]]; then
    echo "" >> "$ANALYSIS_FILE"
    echo "NGINX Access Analysis:" >> "$ANALYSIS_FILE"

    # Top 10 endpoints
    echo "Top 10 endpoints:" >> "$ANALYSIS_FILE"
    awk '{print $7}' "$LOG_DIR/nginx/access.log" | sort | uniq -c | sort -nr | head -10 >> "$ANALYSIS_FILE"

    # HTTP status codes
    echo "" >> "$ANALYSIS_FILE"
    echo "HTTP Status Codes:" >> "$ANALYSIS_FILE"
    awk '{print $9}' "$LOG_DIR/nginx/access.log" | sort | uniq -c | sort -nr >> "$ANALYSIS_FILE"

    # Error rate. These three were `local` at the top level of the script, which bash
    # rejects with "can only be used in a function", so the error rate never printed.
    total=$(wc -l < "$LOG_DIR/nginx/access.log")
    errors=$(awk '$9 >= 400 {print}' "$LOG_DIR/nginx/access.log" | wc -l)
    # awk, not bc: bc is not installed on these nodes, so this line printed
    # "Error Rate: %" with the number missing.
    error_rate=$(awk -v e="$errors" -v t="$total" 'BEGIN { printf "%.2f", (t > 0 ? e * 100 / t : 0) }')
    echo "" >> "$ANALYSIS_FILE"
    echo "Error Rate: ${error_rate}%" >> "$ANALYSIS_FILE"
fi

# Analyze application logs
if journalctl -u "$COORDINATOR_UNIT" --since "1 hour ago" 2>/dev/null | grep -q "ERROR"; then
    echo "" >> "$ANALYSIS_FILE"
    echo "Application Errors (last hour):" >> "$ANALYSIS_FILE"
    journalctl -u "$COORDINATOR_UNIT" --since "1 hour ago" 2>/dev/null | grep "ERROR" | tail -5 >> "$ANALYSIS_FILE"
fi

echo "Analysis complete" >> "$ANALYSIS_FILE"
EOF
    } > "$MONITORING_DIR/analyze_logs.sh"

    chmod +x "$MONITORING_DIR/analyze_logs.sh"
    schedule "0 * * * *" "$MONITORING_DIR/analyze_logs.sh"

    success "Log analysis configured"
}

# Main execution
main() {
    log "Setting up AITBC Production Monitoring..."

    write_monitoring_env
    setup_system_metrics
    setup_alerting
    setup_dashboard
    setup_log_analysis

    success "Production monitoring setup complete!"

    echo
    echo "📊 MONITORING SUMMARY:"
    echo "   ✅ System metrics collection (every 2 minutes)"
    echo "   ✅ Alert checking (every 5 minutes)"
    echo "   ✅ Performance dashboard"
    echo "   ✅ Log analysis (hourly)"
    echo
    echo "🔧 MONITORING COMMANDS:"
    echo "   Dashboard: $MONITORING_DIR/dashboard.sh"
    echo "   Metrics: $MONITORING_DIR/collect_metrics.sh"
    echo "   Alerts: $MONITORING_DIR/check_alerts.sh"
    echo "   Log Analysis: $MONITORING_DIR/analyze_logs.sh"
    echo
    echo "📁 MONITORING FILES:"
    echo "   Config: $MONITORING_ENV"
    echo "   Metrics: $MONITORING_DIR/metrics.log"
    echo "   Alerts: $MONITORING_DIR/alerts.log"
    echo "   Analysis: $MONITORING_DIR/log_analysis.txt"
    echo
    warning "These four are host-level checks. Service health across the platform is"
    warning "scripts/monitoring/health_check.sh, which knows every unit and its port."
}

main "$@"
