#!/usr/bin/env python3
"""Cross-host semantic table digest — stdlib-only remote helper.

Shipped to each fleet node by ``fleet-config-check.sh`` and run against the
node's chain database in read-only mode. Prints one JSON document:

    {"tables": {name: {"class": ..., "digest": ..., "rows": n}},
     "dupes":  {table: [[key..., count], ...]}}

Digest semantics: for every classified table, hash each row's normalized
non-volatile columns, sort the row hashes, and fold them into a table hash —
a multiset comparison that needs no natural key and is immune to row order,
autoincrement ids, and wall-clock stamps. Normalization:

  * address-shaped columns (spec ``addr_cols``) are lowercased — checksum
    and lowercase spellings of one address are a single identity;
  * every other text column passes ``strftime('%Y-%m-%dT%H:%M:%f')``
    normalization with verbatim fallback — T/space separator and sub-second
    drift in stored datetimes compare equal, unparseable values pass
    through unchanged;
  * JSON columns listed in ``json_drop``/``json_drop_falsy`` (currently
    only ``transaction.envelope``) are re-serialized sorted with the listed
    keys removed — see ``block_deltas.DIGEST_JSON_DROP_KEYS`` for why.

The dupes scan groups aux natural keys with address fields lowercased and
reports any key holding more than one row — the v0.25.8 governance-vote
checksum/lowercase twin pattern.

argv: <db_path> <chain_id> <spec_json> [max_height]
spec_json is generated by ``state-digest-spec.py`` on the control host so
every node digests the SAME classification even mid-deploy when their repo
checkouts differ.

``max_height`` bounds every height-scoped row to the fleet-common prefix:
the proposer is often one block ahead of followers when the probe lands, so
without the bound its ``block``/``transaction`` digests flap on timing, not
on state drift. ``-1``/absent means unbounded (and still reports the node's
own ``max_height`` in the output so the driver can pick the bound).
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
import sys

# Columns that bound a row to a block height, first match wins.
_HEIGHT_COLUMNS = ("height", "block_height", "applied_height")


def main() -> int:
    db_path, chain_id, spec = sys.argv[1], sys.argv[2], json.loads(sys.argv[3])
    max_height = int(sys.argv[4]) if len(sys.argv) > 4 else -1
    volatile = frozenset(spec["volatile"])
    addr_cols = frozenset(spec["addr_cols"])
    jdrop = spec.get("json_drop", {})
    jfalsy = spec.get("json_drop_falsy", {})

    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    cur = con.cursor()
    # Parseable datetimes normalize to one canonical text form; anything
    # else (unparseable text, ints, NULL) passes through verbatim.
    dtnorm = 'COALESCE(strftime(\'%Y-%m-%dT%H:%M:%f\',"{}"),"{}")'

    # The node's own sealed height, reported so the driver can compute the
    # fleet-common bound for pass two.
    max_block_height = 0
    try:
        row = cur.execute('SELECT MAX(height) FROM "block" WHERE chain_id=?', (chain_id,)).fetchone()
        max_block_height = int(row[0] or 0)
    except Exception:
        pass
    bound = max_height if max_height >= 0 else max_block_height

    result = {}
    for table in sorted(spec["tables"]):
        meta = spec["tables"][table]
        cls = meta["class"]
        try:
            info = cur.execute(f'PRAGMA table_info("{table}")').fetchall()
        except Exception as e:  # pragma: no cover - defensive
            result[table] = {"class": cls, "error": str(e)}
            continue
        if not info:
            result[table] = {"class": cls, "missing": 1}
            continue
        names = [c[1] for c in info]
        allow = meta.get("allow")
        keep = [n for n in names if n not in volatile and (allow is None or n in allow)]
        if not keep:
            result[table] = {"class": cls, "empty_cols": 1}
            continue
        sel = ", ".join(
            f'lower("{n}")' if n in addr_cols else f'"{n}"' if n in jdrop or n in jfalsy else dtnorm.format(n, n) for n in keep
        )
        where, args = "", ()
        if "chain_id" in names:
            where, args = "WHERE chain_id=?", (chain_id,)
        elif "source_chain" in names:
            where, args = "WHERE source_chain=?", (chain_id,)
        # Height-scope the row to the fleet-common prefix when the table has
        # a height column (block.height, transaction.block_height,
        # chain_parameter_history.applied_height, ...). Tables without one
        # are current-state rows — the block.state_root column inside the
        # bounded block digest already proves their equivalence at the bound.
        hcol = next((c for c in _HEIGHT_COLUMNS if c in names), None)
        if hcol is not None:
            where += " AND " if where else "WHERE "
            if hcol == "applied_height":
                # NULL applied_height means "in force at every height" —
                # it is part of the prefix state, not a future row.
                where += '("applied_height" IS NULL OR "applied_height" <= ?)'
            else:
                where += f'"{hcol}" <= ?'
            args += (bound,)
        q = f'SELECT {sel} FROM "{table}" {where}'  # nosec B608 - identifiers only, values bound

        def _norm(row: tuple, keep: list = keep, jdrop: dict = jdrop, jfalsy: dict = jfalsy) -> tuple:
            r = list(row)
            for i, n in enumerate(keep):
                if (n in jdrop or n in jfalsy) and isinstance(r[i], str) and r[i][:1] == "{":
                    try:
                        obj = json.loads(r[i])
                    except Exception:
                        continue
                    if isinstance(obj, dict):
                        for k in jdrop.get(n, ()):
                            obj.pop(k, None)
                        for k in jfalsy.get(n, ()):
                            if not obj.get(k):
                                obj.pop(k, None)
                        r[i] = json.dumps(obj, sort_keys=True, separators=(",", ":"))
            return tuple(r)

        try:
            rows = cur.execute(q, args).fetchall()
        except Exception as e:
            result[table] = {"class": cls, "error": str(e)}
            continue
        h = hashlib.sha256()
        n = 0
        for rh in sorted(hashlib.sha256(repr(_norm(r)).encode()).hexdigest() for r in rows):
            h.update(rh.encode())
            h.update(b"\x00")
            n += 1
        result[table] = {"class": cls, "digest": h.hexdigest()[:16], "rows": n}

    dupes = {}
    for table, dk in spec.get("dupkeys", {}).items():
        try:
            info = cur.execute(f'PRAGMA table_info("{table}")').fetchall()
        except Exception:
            continue
        names = {c[1] for c in info}
        key = dk["key"]
        addr = set(dk["addr"])
        # Only natural keys containing an address column can split on case.
        if not key or not all(k in names for k in key) or not (set(key) & addr):
            continue
        grp = ", ".join(f'lower("{k}")' if k in addr else f'"{k}"' for k in key)
        w = "WHERE chain_id=?" if "chain_id" in names else ""
        args = (chain_id,) if w else ()
        # nosec on next line: only schema-derived identifiers interpolate; values stay bound
        q = f'SELECT {grp}, COUNT(*) c FROM "{table}" {w} GROUP BY {grp} HAVING c>1'  # nosec B608
        try:
            hits = [list(r) for r in cur.execute(q, args)]
        except Exception:
            continue
        if hits:
            dupes[table] = hits

    print(json.dumps({"max_height": max_block_height, "bound": bound, "tables": result, "dupes": dupes}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
