FROM otel/opentelemetry-collector-contrib:0.118.0

COPY --chmod=644 otel-collector-config.yaml /etc/otelcol-contrib/config.yaml

EXPOSE 4317 4318 13133 8889

CMD ["--config=/etc/otelcol-contrib/config.yaml"]