name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: debian:host 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          hostname
          node -v || true
          npm -v || true

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build || echo "no build step"
