name: ci

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: debian

    steps:
      - name: Clone repository
        run: |
          rm -rf repo
          git clone https://gitea.bubuit.net/oib/aitbc.git repo

      - name: Enter repo + debug
        run: |
          cd repo
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la

      - name: Install dependencies
        run: |
          cd repo
          npm install --legacy-peer-deps

      - name: Build
        run: |
          cd repo
          npm run build || echo "no build"
