"""AITBC Package - Centralized utilities for AITBC applications."""

from __future__ import annotations

from ._version import __version__
from .aitbc_logging import configure_logging, get_blockchain_logger, get_logger, setup_logger
from .constants import (
    AGENT_COORDINATOR_PORT,
    BLOCKCHAIN_DATA_DIR,
    BLOCKCHAIN_P2P_PORT,
    BLOCKCHAIN_RPC_PORT,
    CONFIG_DIR,
    DATA_DIR,
    ENV_FILE,
    KEYSTORE_DIR,
    LOG_DIR,
    MARKETPLACE_DATA_DIR,
    MARKETPLACE_PORT,
    NODE_ENV_FILE,
    PACKAGE_VERSION,
    REPO_DIR,
)
from .exceptions import (
    AITBCError,
    AuthenticationError,
    BridgeError,
    CircuitBreakerOpenError,
    ConfigurationError,
    DatabaseError,
    EncryptionError,
    NetworkError,
    RateLimitError,
    RetryError,
    ValidationError,
)
from .middleware import (
    ErrorHandlerMiddleware,
    PerformanceLoggingMiddleware,
    RequestIDMiddleware,
    RequestValidationMiddleware,
)
from .utils.env import (
    get_bool_env_var,
    get_env_var,
    get_float_env_var,
    get_int_env_var,
    get_list_env_var,
    get_required_env_var,
)
from .utils.paths import (
    ensure_dir,
    ensure_file_dir,
    get_blockchain_data_path,
    get_config_path,
    get_data_path,
    get_keystore_path,
    get_log_path,
    get_marketplace_data_path,
    get_repo_path,
    resolve_path,
)

__all__ = [
    "__version__",
    "get_logger",
    "get_blockchain_logger",
    "configure_logging",
    "setup_logger",
    "DATA_DIR",
    "CONFIG_DIR",
    "LOG_DIR",
    "REPO_DIR",
    "KEYSTORE_DIR",
    "BLOCKCHAIN_DATA_DIR",
    "MARKETPLACE_DATA_DIR",
    "ENV_FILE",
    "NODE_ENV_FILE",
    "BLOCKCHAIN_RPC_PORT",
    "BLOCKCHAIN_P2P_PORT",
    "AGENT_COORDINATOR_PORT",
    "MARKETPLACE_PORT",
    "PACKAGE_VERSION",
    "AITBCError",
    "ConfigurationError",
    "NetworkError",
    "AuthenticationError",
    "EncryptionError",
    "DatabaseError",
    "ValidationError",
    "BridgeError",
    "RetryError",
    "CircuitBreakerOpenError",
    "RateLimitError",
    "ErrorHandlerMiddleware",
    "PerformanceLoggingMiddleware",
    "RequestIDMiddleware",
    "RequestValidationMiddleware",
    "get_env_var",
    "get_required_env_var",
    "get_bool_env_var",
    "get_int_env_var",
    "get_float_env_var",
    "get_list_env_var",
    "get_data_path",
    "get_config_path",
    "get_log_path",
    "get_repo_path",
    "ensure_dir",
    "ensure_file_dir",
    "resolve_path",
    "get_keystore_path",
    "get_blockchain_data_path",
    "get_marketplace_data_path",
]
