"""Bootstrap commands for builder environments (v0.16.1 §B1)."""

from __future__ import annotations

from pathlib import Path

import click

from ..services.env_validator import validate_env
from ..utils import output, success, warning


@click.group()
def bootstrap():
    """Bootstrap local development and configuration files."""
    pass


@bootstrap.command("bootstrap-env")
@click.option("--output", "output_path", default=".env", help="Output .env file path")
@click.option("--overwrite", is_flag=True, help="Overwrite existing .env")
@click.pass_context
def bootstrap_env(ctx, output_path: str, overwrite: bool):
    """Generate a starter .env file and validate it."""
    target = Path(output_path)
    if target.exists() and not overwrite:
        warning(f"{output_path} already exists; use --overwrite to replace")
        ctx.exit(1)

    lines = [
        "# AITBC builder environment - generated by aitbc bootstrap-env",
        "# Set real values before running services",
        "",
        "AITBC_API_KEY=",
        "COORDINATOR_API_URL=http://localhost:8000",
        "",
        "# Optional service keys",
        "# OPENAI_API_KEY=",
        "# EXCHANGE_API_KEY=",
        "",
    ]
    target.write_text("\n".join(lines), encoding="utf-8")

    # Read back as a dict and validate the template (it will be missing required keys).
    env: dict[str, str] = {}
    for line in lines:
        if line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip()

    result = validate_env(env, allow_missing=True)

    if ctx.obj["output"] == "table":
        success(f"Starter .env written to {output_path}")
        if result.missing:
            warning(f"Fill in missing keys: {', '.join(result.missing)}")

    output(
        {
            "output_path": str(target.resolve()),
            "missing": result.missing,
            "valid": result.valid,
            "status": "generated",
        },
        ctx.obj["output"],
    )
