"""
Utility functions for AITBC
Provides validation, time utilities, JSON utilities, path utilities, and environment variable utilities
"""

from .env import get_bool_env_var, get_env_var, get_float_env_var, get_int_env_var, get_list_env_var, get_required_env_var
from .json_utils import (
    flatten_json,
    get_nested_value,
    json_to_string,
    load_json,
    merge_json,
    save_json,
    set_nested_value,
    string_to_json,
)
from .paths import (
    ensure_dir,
    ensure_file_dir,
    get_blockchain_data_path,
    get_config_path,
    get_data_path,
    get_keystore_path,
    get_log_path,
    get_marketplace_data_path,
    get_repo_path,
    resolve_path,
)
from .time_utils import (
    Timer,
    add_duration,
    calculate_deadline,
    format_duration,
    format_duration_precise,
    format_iso8601,
    format_time_ago,
    format_time_in,
    get_deadline_remaining,
    get_end_of_day,
    get_end_of_month,
    get_end_of_week,
    get_start_of_day,
    get_start_of_month,
    get_start_of_week,
    get_time_since,
    get_time_until,
    get_timestamp_utc,
    get_timezone_offset,
    get_utc_now,
    is_business_hours,
    is_deadline_passed,
    iso_to_timestamp,
    parse_duration,
    parse_iso8601,
    retry_until_deadline,
    sleep_until,
    subtract_duration,
    timestamp_to_iso,
    to_timezone,
)
from .validation import (
    validate_address,
    validate_chain_id,
    validate_email,
    validate_hash,
    validate_non_empty,
    validate_port,
    validate_positive_number,
    validate_range,
    validate_url,
    validate_uuid,
)

__all__ = [
    # Validation
    "validate_address",
    "validate_hash",
    "validate_url",
    "validate_port",
    "validate_email",
    "validate_non_empty",
    "validate_positive_number",
    "validate_range",
    "validate_chain_id",
    "validate_uuid",
    # Time utils
    "Timer",
    "get_utc_now",
    "get_timestamp_utc",
    "format_iso8601",
    "parse_iso8601",
    "timestamp_to_iso",
    "iso_to_timestamp",
    "format_duration",
    "format_duration_precise",
    "parse_duration",
    "add_duration",
    "subtract_duration",
    "get_time_until",
    "get_time_since",
    "calculate_deadline",
    "is_deadline_passed",
    "get_deadline_remaining",
    "format_time_ago",
    "format_time_in",
    "to_timezone",
    "get_timezone_offset",
    "is_business_hours",
    "get_start_of_day",
    "get_end_of_day",
    "get_start_of_week",
    "get_end_of_week",
    "get_start_of_month",
    "get_end_of_month",
    "sleep_until",
    "retry_until_deadline",
    # JSON utils
    "load_json",
    "save_json",
    "merge_json",
    "json_to_string",
    "string_to_json",
    "get_nested_value",
    "set_nested_value",
    "flatten_json",
    # Paths
    "get_data_path",
    "get_config_path",
    "get_log_path",
    "get_repo_path",
    "ensure_dir",
    "ensure_file_dir",
    "resolve_path",
    "get_keystore_path",
    "get_blockchain_data_path",
    "get_marketplace_data_path",
    # Environment
    "get_env_var",
    "get_required_env_var",
    "get_bool_env_var",
    "get_int_env_var",
    "get_float_env_var",
    "get_list_env_var",
]
