#!/usr/bin/env bash
# install-nginx-node.sh
# Run this on any island node to expose AITBC services via nginx.
# Works for aitbc3, aitbc4, any future node — no manual editing required.
#
# Usage: sudo bash /opt/aitbc/scripts/setup/install-nginx-node.sh
set -euo pipefail

AITBC_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
NGINX_CONF_SRC="$AITBC_DIR/deployment/nginx-aitbc.conf"
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available/aitbc"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled/aitbc"
NGINX_OVERRIDE="/etc/nginx/conf.d/aitbc-hostname.conf"

# Detect node identity
NODE_HOSTNAME="$(hostname -f 2>/dev/null || hostname)"
# Derive domain from hub_discovery_url in aitbc config, fall back to env
AITBC_CONFIG="/etc/aitbc/node.env"
HUB_DISCOVERY_URL=""
if [[ -f "$AITBC_CONFIG" ]]; then
    HUB_DISCOVERY_URL="$(grep -E '^HUB_DISCOVERY_URL=' "$AITBC_CONFIG" | cut -d= -f2- | tr -d '"' || true)"
fi
HUB_HOST="${HUB_DISCOVERY_URL:-hub.aitbc.bubuit.net}"
BASE_DOMAIN="${HUB_HOST#hub.}"

SERVER_NAME="${NODE_HOSTNAME}.${BASE_DOMAIN} ${NODE_HOSTNAME}"

echo "→ Node hostname : $NODE_HOSTNAME"
echo "→ Base domain   : $BASE_DOMAIN"
echo "→ nginx server_name: $SERVER_NAME"

# Install main config
cp "$NGINX_CONF_SRC" "$NGINX_SITES_AVAILABLE"
ln -sf "$NGINX_SITES_AVAILABLE" "$NGINX_SITES_ENABLED"

# Write per-node hostname override (nginx conf.d loads before sites)
cat > "$NGINX_OVERRIDE" <<EOF
# Auto-generated by install-nginx-node.sh — do not edit manually
# Re-run the script after hostname/domain changes.
server_name_in_redirect off;
EOF

# Patch server_name inside the aitbc site config for this node
sed -i "s/server_name _;/server_name ${SERVER_NAME};/" "$NGINX_SITES_AVAILABLE"

# Test and reload
nginx -t
systemctl reload nginx

echo ""
echo "✓ nginx configured for node: $SERVER_NAME"
echo ""
echo "Services now available at:"
echo "  http://${NODE_HOSTNAME}.${BASE_DOMAIN}/whisper/health"
echo "  http://${NODE_HOSTNAME}.${BASE_DOMAIN}/ollama/api/tags"
echo "  http://${NODE_HOSTNAME}.${BASE_DOMAIN}/rpc/"
echo "  http://${NODE_HOSTNAME}.${BASE_DOMAIN}/agent/health"
