# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 1 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _collect_options,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_health(
    host_opt: Annotated[str, Field(description="Remote host to probe (hostname, IP, or http(s):// URL).")],
    services: Annotated[
        str | None, Field(description="Comma-separated list of services to probe (default: all known AITBC services).")
    ],
    timeout_opt: Annotated[float | None, Field(description="Timeout per request in seconds.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Probe AITBC service health endpoints on a remote host.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"host_opt": "host", "services": "services", "timeout_opt": "timeout"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "health",
        subcommand=None,
        args=args,
        options=options,
        timeout=timeout,
    )
