# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 8 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_coin_requests_approve(
    request_id: Annotated[str, Field(description="The Request id.")],
    reason: Annotated[str | None, Field(description="Reason for approval")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Approve a pending coin transfer request by request ID.."""
    options: dict[str, Any] = {}
    if request_id is not None:
        options["request-id"] = request_id
    if reason is not None:
        options["reason"] = reason
    args = None
    command = _build_aitbc_cli_command(
        "coin-requests",
        subcommand=["approve"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "coin-requests",
            subcommand=["approve"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_coin_requests_execute(
    request_id: Annotated[str, Field(description="The Request id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Execute an approved coin transfer request by submitting a signed transaction.."""
    options: dict[str, Any] = {}
    if request_id is not None:
        options["request-id"] = request_id
    args = None
    command = _build_aitbc_cli_command(
        "coin-requests",
        subcommand=["execute"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "coin-requests",
            subcommand=["execute"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_coin_requests_list(
    status: Annotated[str | None, Field(description="Filter by status (pending, approved, rejected, expired)")],
    sender: Annotated[str | None, Field(description="Filter by sender")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List coin transfer requests with optional status and sender filters.."""
    options: dict[str, Any] = {}
    if status is not None:
        options["status"] = status
    if sender is not None:
        options["sender"] = sender
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "coin-requests",
        subcommand=["list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_coin_requests_reconcile(
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC to check against (defaults to BLOCKCHAIN_RPC_URL)")],
    annotate: Annotated[bool | None, Field(description="Record the discrepancy in each affected request's audit log")],
    chain_id: Annotated[str | None, Field(description="Island to query; omit to let the node answer for its own chain")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Check executed coin requests against the chain and report or annotate discrepancies.."""
    options: dict[str, Any] = {}
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    if annotate:
        options["annotate"] = None
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "coin-requests",
        subcommand=["reconcile"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "coin-requests",
            subcommand=["reconcile"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_coin_requests_reject(
    request_id: Annotated[str, Field(description="The Request id.")],
    reason: Annotated[str, Field(description="Reason for rejection")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Reject a pending coin transfer request with a required reason.."""
    options: dict[str, Any] = {}
    if request_id is not None:
        options["request-id"] = request_id
    if reason is not None:
        options["reason"] = reason
    args = None
    command = _build_aitbc_cli_command(
        "coin-requests",
        subcommand=["reject"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "coin-requests",
            subcommand=["reject"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_coin_requests_reopen(
    request_id: Annotated[str, Field(description="The Request id.")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC to check against (defaults to BLOCKCHAIN_RPC_URL)")],
    force: Annotated[bool | None, Field(description="Reopen even though the chain still has the transaction")],
    chain_id: Annotated[str | None, Field(description="Island to query; omit to let the node answer for its own chain")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Clear a request's transaction hash so it can be executed again.."""
    options: dict[str, Any] = {}
    if request_id is not None:
        options["request-id"] = request_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    if force:
        options["force"] = None
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "coin-requests",
        subcommand=["reopen"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "coin-requests",
            subcommand=["reopen"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_coin_requests_request(
    wallet: Annotated[str | None, Field(description="Wallet name to receive the coins.")],
    amount: Annotated[int | None, Field(description="Amount in AIT.")],
    sender: Annotated[str | None, Field(description="Sender id (defaults to hostname-wallet-suffix).")],
    recipient: Annotated[str | None, Field(description="Recipient agent id.")],
    request_id: Annotated[str | None, Field(description="Request id (defaults to a unique value).")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Request a one-time initial coin grant from the hub for a local wallet.."""
    options: dict[str, Any] = {}
    if wallet is not None:
        options["wallet"] = wallet
    if amount is not None:
        options["amount"] = amount
    if sender is not None:
        options["sender"] = sender
    if recipient is not None:
        options["recipient"] = recipient
    if request_id is not None:
        options["request-id"] = request_id
    args = None
    command = _build_aitbc_cli_command(
        "coin-requests",
        subcommand=["request"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "coin-requests",
            subcommand=["request"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_coin_requests_show(
    request_id: Annotated[str, Field(description="The Request id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show details of a specific coin transfer request.."""
    options: dict[str, Any] = {}
    if request_id is not None:
        options["request-id"] = request_id
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "coin-requests",
        subcommand=["show"],
        args=args,
        options=options,
        timeout=timeout,
    )
