# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 2 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_contract_call(
    contract_address: Annotated[str, Field(description="Contract address")],
    method: Annotated[str, Field(description="Method to call")],
    args: Annotated[str | None, Field(description="Method arguments (JSON array)")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Call a method on a deployed smart contract with optional arguments.."""
    options: dict[str, Any] = {}
    if contract_address is not None:
        options["contract-address"] = contract_address
    if method is not None:
        options["method"] = method
    if args is not None:
        options["args"] = args
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "contract",
        subcommand=["call"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "contract",
            subcommand=["call"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_contract_deploy(
    contract_name: Annotated[str, Field(description="Contract name")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Deploy a named smart contract to the blockchain.."""
    options: dict[str, Any] = {}
    if contract_name is not None:
        options["contract-name"] = contract_name
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "contract",
        subcommand=["deploy"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "contract",
            subcommand=["deploy"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
