# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 6 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_prometheus_alerts(
    prometheus_url: Annotated[str | None, Field(description="Prometheus base URL (default: http://127.0.0.1:9090)")],
    watch: Annotated[bool | None, Field(description="Poll continuously and emit firing alerts")],
    interval: Annotated[int | None, Field(description="Poll interval in seconds (watch mode)")],
    emit: Annotated[bool | None, Field(description="Emit one structured log line per firing alert (watch mode)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show current Prometheus alerts and optionally watch for firing alerts.."""
    options: dict[str, Any] = {}
    if prometheus_url is not None:
        options["prometheus-url"] = prometheus_url
    if watch:
        options["watch"] = None
    if interval is not None:
        options["interval"] = interval
    if emit:
        options["emit"] = None
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "prometheus",
        subcommand=["alerts"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_prometheus_check(
    config_path: Annotated[str | None, Field(description="Prometheus config file")],
    rules_path: Annotated[str | None, Field(description="Prometheus rules file")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Validate Prometheus config and rules with promtool.."""
    options: dict[str, Any] = {}
    if config_path is not None:
        options["config"] = config_path
    if rules_path is not None:
        options["rules"] = rules_path
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "prometheus",
        subcommand=["check"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_prometheus_query(
    expr: Annotated[str, Field(description="The Expr.")],
    prometheus_url: Annotated[str | None, Field(description="Prometheus base URL (default: http://127.0.0.1:9090)")],
    time: Annotated[str | None, Field(description="Evaluation timestamp (RFC3339 or Unix)")],
    timeout_opt: Annotated[int | None, Field(description="Query timeout in seconds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Run a PromQL query against Prometheus.."""
    options: dict[str, Any] = {}
    if expr is not None:
        options["expr"] = expr
    if prometheus_url is not None:
        options["prometheus-url"] = prometheus_url
    if time is not None:
        options["time"] = time
    if timeout_opt is not None:
        options["timeout"] = timeout_opt
    args = None
    command = _build_aitbc_cli_command(
        "prometheus",
        subcommand=["query"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "prometheus",
            subcommand=["query"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_prometheus_rules(
    prometheus_url: Annotated[str | None, Field(description="Prometheus base URL (default: http://127.0.0.1:9090)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List loaded Prometheus recording and alerting rules.."""
    options: dict[str, Any] = {}
    if prometheus_url is not None:
        options["prometheus-url"] = prometheus_url
    args = None
    command = _build_aitbc_cli_command(
        "prometheus",
        subcommand=["rules"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "prometheus",
            subcommand=["rules"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_prometheus_series(
    prometheus_url: Annotated[str | None, Field(description="Prometheus base URL (default: http://127.0.0.1:9090)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Show the count of currently loaded metric series for cardinality.."""
    options: dict[str, Any] = {}
    if prometheus_url is not None:
        options["prometheus-url"] = prometheus_url
    args = None
    command = _build_aitbc_cli_command(
        "prometheus",
        subcommand=["series"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "prometheus",
            subcommand=["series"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_prometheus_targets(
    prometheus_url: Annotated[str | None, Field(description="Prometheus base URL (default: http://127.0.0.1:9090)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Show the health of every Prometheus scrape target.."""
    options: dict[str, Any] = {}
    if prometheus_url is not None:
        options["prometheus-url"] = prometheus_url
    args = None
    command = _build_aitbc_cli_command(
        "prometheus",
        subcommand=["targets"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "prometheus",
            subcommand=["targets"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
