# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 5 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_msg_peers(
    coordinator_url: Annotated[str | None, Field(description="Agent Coordinator URL (default: from config)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List the peers currently known to the Agent Coordinator.."""
    options: dict[str, Any] = {}
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-msg",
        subcommand=["peers"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_msg_ping(
    agent: Annotated[str | None, Field(description="Recipient agent ID to ping")],
    sender: Annotated[str | None, Field(description="Sender agent ID (your agent ID for the WebSocket connection)")],
    coordinator_url: Annotated[
        str | None,
        Field(
            description="Agent Coordinator URL. Direct: http://localhost:8107. Via nginx on the hub: https://hub.aitbc.bubuit.net/agent (default: from config agent_coordinator_url)"
        ),
    ],
    timeout_opt: Annotated[int | None, Field(description="Seconds to wait for a PONG reply")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Ping a remote agent via WebSocket and wait for its PONG reply.."""
    options: dict[str, Any] = {}
    if agent is not None:
        options["agent"] = agent
    if sender is not None:
        options["sender"] = sender
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    if timeout_opt is not None:
        options["timeout"] = timeout_opt
    args = None
    command = _build_aitbc_cli_command(
        "agent-msg",
        subcommand=["ping"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-msg",
            subcommand=["ping"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_msg_receive(
    from_agent: Annotated[str | None, Field(description="Agent ID whose inbox to read (default: $AGENT_ID)")],
    limit: Annotated[int | None, Field(description="Number of messages to return")],
    unread_only: Annotated[bool | None, Field(description="Only return unread messages")],
    coordinator_url: Annotated[str | None, Field(description="Agent Coordinator URL (default: from config)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Receive messages from the Agent Coordinator inbox for the configured agent.."""
    options: dict[str, Any] = {}
    if from_agent is not None:
        options["from-agent"] = from_agent
    if limit is not None:
        options["limit"] = limit
    if unread_only:
        options["unread-only"] = None
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "agent-msg",
        subcommand=["receive"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-msg",
            subcommand=["receive"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_msg_request_coins(
    wallet: Annotated[
        str | None, Field(description="Wallet name to send coins to (default: auto-detect first available wallet)")
    ],
    amount: Annotated[
        int | None,
        Field(description="Amount of AIT to request (first request auto-grants 100; subsequent require manual approval)"),
    ],
    sender: Annotated[str | None, Field(description="Sender agent ID (your agent ID for the WebSocket connection)")],
    coordinator_url: Annotated[
        str | None,
        Field(
            description="Agent Coordinator URL. Direct: http://localhost:8107. Via nginx on the hub: https://hub.aitbc.bubuit.net/agent (default: from config agent_coordinator_url)"
        ),
    ],
    timeout_opt: Annotated[int | None, Field(description="Seconds to wait for a response")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Request free AIT tokens from the hub via WebSocket for the configured wallet.."""
    options: dict[str, Any] = {}
    if wallet is not None:
        options["wallet"] = wallet
    if amount is not None:
        options["amount"] = amount
    if sender is not None:
        options["sender"] = sender
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    if timeout_opt is not None:
        options["timeout"] = timeout_opt
    args = None
    command = _build_aitbc_cli_command(
        "agent-msg",
        subcommand=["request-coins"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-msg",
            subcommand=["request-coins"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_msg_send(
    message: Annotated[str, Field(description="Positional argument: message")],
    to_agent: Annotated[str, Field(description="Target agent ID")],
    from_agent: Annotated[str | None, Field(description="Sender agent ID (default: $AGENT_ID)")],
    priority: Annotated[str | None, Field(description="Message priority")],
    message_id: Annotated[str | None, Field(description="Client-provided message ID for idempotent sends")],
    message_type: Annotated[str | None, Field(description="Message type")],
    ttl: Annotated[int | None, Field(description="Time to live in seconds")],
    encrypt: Annotated[bool | None, Field(description="Encrypt the message")],
    coordinator_url: Annotated[str | None, Field(description="Agent Coordinator URL (default: from config)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Send a direct or broadcast message to another agent through the coordinator.."""
    options: dict[str, Any] = {}
    if from_agent is not None:
        options["from-agent"] = from_agent
    if to_agent is not None:
        options["to-agent"] = to_agent
    if priority is not None:
        options["priority"] = priority
    if message_id is not None:
        options["message-id"] = message_id
    if message_type is not None:
        options["message-type"] = message_type
    if ttl is not None:
        options["ttl"] = ttl
    if encrypt:
        options["encrypt"] = None
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = [message] if message is not None else []
    command = _build_aitbc_cli_command(
        "agent-msg",
        subcommand=["send"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-msg",
            subcommand=["send"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
