# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 3 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_wallet_balance(
    agent_id: Annotated[str, Field(description="Agent ID.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show the wallet balance and allocation for a given agent ID.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-wallet",
        subcommand=["balance"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_wallet_rebalance(
    agent_id: Annotated[str, Field(description="Agent ID.")],
    earnings: Annotated[str | None, Field(description="Earnings to reinvest")],
    reinvest_pct: Annotated[str | None, Field(description="Percentage of earnings to reinvest")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Rebalance an agent wallet by reinvesting the specified earnings.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    if earnings is not None:
        options["earnings"] = earnings
    if reinvest_pct is not None:
        options["reinvest-pct"] = reinvest_pct
    args = None
    command = _build_aitbc_cli_command(
        "agent-wallet",
        subcommand=["rebalance"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-wallet",
            subcommand=["rebalance"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_wallet_stake(
    agent_id: Annotated[str, Field(description="Agent ID.")],
    amount: Annotated[str | None, Field(description="Amount to stake")],
    contract: Annotated[str | None, Field(description="Staking contract address")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Stake AITBC on behalf of a specified agent ID.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    if amount is not None:
        options["amount"] = amount
    if contract is not None:
        options["contract"] = contract
    args = None
    command = _build_aitbc_cli_command(
        "agent-wallet",
        subcommand=["stake"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-wallet",
            subcommand=["stake"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
