# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 26 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _collect_options,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_address(
    name: Annotated[str | None, Field(description="Wallet name.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Display the public address of the active or named wallet.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"name": "name"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["address"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_backup(
    name: Annotated[str, Field(description="Wallet name.")],
    destination: Annotated[str | None, Field(description="Destination path for backup file")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Export a wallet to a password-encrypted backup file at the given path.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"name": "name", "destination": "destination"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["backup"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["backup"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_balance(
    name: Annotated[str | None, Field(description="Wallet name.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Check the AITBC balance of a wallet from the blockchain RPC.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"name": "name"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["balance"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_bridge_deposit(
    amount: Annotated[str, Field(description="ETH amount to deposit.")],
    wallet_name: Annotated[str | None, Field(description="Source wallet name for ETH signing.")],
    eth_rpc_url: Annotated[str | None, Field(description="Ethereum RPC URL.")],
    password: Annotated[str | None, Field(description="Wallet password for signing")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Deposit ETH to the bridge and receive AITBC on the hub.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"amount": "amount", "wallet_name": "wallet-name", "eth_rpc_url": "eth-rpc-url", "password": "password"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["bridge", "deposit"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["bridge", "deposit"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_bridge_status(
    ait_tx_hash: Annotated[str, Field(description="AIT withdrawal transaction hash.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Check the status of an AIT->ETH withdrawal.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"ait_tx_hash": "ait-tx-hash"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["bridge", "status"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_bridge_withdraw(
    amount: Annotated[str, Field(description="AIT amount to withdraw.")],
    eth_address: Annotated[str, Field(description="Destination Ethereum address.")],
    wallet_name: Annotated[str | None, Field(description="Source wallet name for AIT signing.")],
    password: Annotated[str | None, Field(description="Wallet password for signing")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Burn AITBC on the hub to receive ETH at the given Ethereum address.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"amount": "amount", "eth_address": "eth-address", "wallet_name": "wallet-name", "password": "password"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["bridge", "withdraw"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["bridge", "withdraw"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_create(
    name: Annotated[str, Field(description="Wallet name.")],
    wallet_type: Annotated[str | None, Field(description="Wallet type (hd, simple)")],
    no_encrypt: Annotated[bool | None, Field(description="Skip wallet encryption (not recommended)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create a new wallet with an optional type and password encryption.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"no_encrypt": "no-encrypt"},
        values={"name": "name", "wallet_type": "type"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["create"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["create"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_earn(
    amount: Annotated[str, Field(description="Amount of AIT.")],
    job_id: Annotated[str, Field(description="Coordinator job ID.")],
    desc: Annotated[str | None, Field(description="Description of the work")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Record earnings received for a completed job against the wallet.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"amount": "amount", "job_id": "job-id", "desc": "desc"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["earn"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["earn"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_export(
    destination: Annotated[str | None, Field(description="Destination file path (default: wallet_name_export.json)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Export the active wallet to a JSON file at the given destination.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"destination": "destination"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["export"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["export"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_info(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show detailed information about the currently active wallet.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["info"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_liquidity_claim(
    stake_id: Annotated[str, Field(description="Stake ID.")],
    fee: Annotated[str | None, Field(description="Transaction fee in AIT")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Claim accrued liquidity rewards for the given stake ID.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"stake_id": "stake-id", "fee": "fee"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["liquidity-claim"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["liquidity-claim"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_liquidity_stake(
    amount: Annotated[str, Field(description="Amount of AIT.")],
    pool: Annotated[str | None, Field(description="Liquidity pool name")],
    lock_days: Annotated[int | None, Field(description="Lock period in days (higher APY)")],
    fee: Annotated[str | None, Field(description="Transaction fee in AIT")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Stake tokens into an on-chain liquidity pool to earn rewards.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"amount": "amount", "pool": "pool", "lock_days": "lock-days", "fee": "fee"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["liquidity-stake"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["liquidity-stake"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_liquidity_unstake(
    stake_id: Annotated[str, Field(description="Stake ID.")],
    fee: Annotated[str | None, Field(description="Transaction fee in AIT")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Withdraw a liquidity stake and its accumulated rewards.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"stake_id": "stake-id", "fee": "fee"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["liquidity-unstake"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["liquidity-unstake"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_list(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List all locally stored wallets and their active chain addresses.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_multisig_create(
    signers: Annotated[list[str], Field(description="One or more signer addresses.")],
    threshold: Annotated[int, Field(description="Required signatures to approve")],
    name: Annotated[str, Field(description="Multisig wallet name")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create a multi-signature wallet with a threshold and a list of signers.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"signers": "signers", "threshold": "threshold", "name": "name"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["multisig-create"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["multisig-create"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_multisig_propose(
    wallet_name: Annotated[str, Field(description="Multisig wallet name")],
    to_address: Annotated[str, Field(description="Destination address.")],
    amount: Annotated[str, Field(description="Amount of AIT.")],
    description: Annotated[str | None, Field(description="Transaction description")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Propose a multi-signature payment to a destination address.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"wallet_name": "wallet", "to_address": "to-address", "amount": "amount", "description": "description"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["multisig-propose"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["multisig-propose"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_multisig_sign(
    wallet_name: Annotated[str, Field(description="Multisig wallet name")],
    tx_id: Annotated[str, Field(description="Transaction ID.")],
    signer: Annotated[str, Field(description="Signer address")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Sign a pending multi-signature transaction with the given signer address.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"wallet_name": "wallet", "tx_id": "tx-id", "signer": "signer"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["multisig-sign"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["multisig-sign"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_request_payment(
    to_address: Annotated[str, Field(description="Destination address.")],
    amount: Annotated[str, Field(description="Amount of AIT.")],
    description: Annotated[str | None, Field(description="Transaction description")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Generate a payment request to another address for a specific amount.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"to_address": "to-address", "amount": "amount", "description": "description"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["request-payment"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["request-payment"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_restore(
    backup_path: Annotated[str, Field(description="Path to the backup file.")],
    name: Annotated[str, Field(description="Wallet name.")],
    force: Annotated[bool | None, Field(description="Override existing wallet")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Restore a wallet from a backup file with an optional force override.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"force": "force"},
        values={"backup_path": "backup-path", "name": "name"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["restore"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["restore"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_send(
    to_address: Annotated[str, Field(description="Destination address.")],
    amount: Annotated[str, Field(description="Amount of AIT.")],
    fee: Annotated[str | None, Field(description="Transaction fee in AIT")],
    password: Annotated[str | None, Field(description="Wallet password for signing")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Send AITBC tokens from the active wallet to another address.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"to_address": "to-address", "amount": "amount", "fee": "fee", "password": "password", "rpc_url": "rpc-url"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["send"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["send"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_spend(
    amount: Annotated[str, Field(description="Amount of AIT.")],
    description: Annotated[str, Field(description="Free-form description.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Record a manual spend transaction with an amount and description.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"amount": "amount", "description": "description"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["spend"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["spend"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_stake(
    amount: Annotated[str, Field(description="Amount of AIT.")],
    duration: Annotated[int | None, Field(description="Staking duration in days")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Stake AITBC tokens on the blockchain for a configurable duration.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"amount": "amount", "duration": "duration"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["stake"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["stake"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_stats(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show aggregated statistics for the active wallet over all transactions.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["stats"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_switch(
    name: Annotated[str, Field(description="Wallet name.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Switch the active wallet context to a different locally stored wallet.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"name": "name"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["switch"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["switch"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_wallet_transactions(
    name: Annotated[str | None, Field(description="Wallet name.")],
    limit: Annotated[int | None, Field(description="Number of transactions to show")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List recent blockchain transactions for the active or named wallet.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"name": "name", "limit": "limit"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "wallet",
        subcommand=["transactions"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_wallet_unstake(
    stake_id: Annotated[str, Field(description="Stake ID.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Unstake tokens and withdraw the principal for the given stake ID.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"stake_id": "stake-id"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "wallet",
        subcommand=["unstake"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "wallet",
            subcommand=["unstake"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
