# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 6 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_tee_attest(
    enclave_id: Annotated[str, Field(description="The Enclave-id.")],
    measurement: Annotated[str | None, Field(description="Expected enclave measurement")],
    key_file: Annotated[
        str | None,
        Field(
            description="Path to a stable signing key (see 'aitbc tee keygen'). Without this, each call signs with a fresh random key, so there is nothing stable here for 'aitbc tee register' to pin against."
        ),
    ],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Attest a TEE enclave and verify its measurement.."""
    options: dict[str, Any] = {}
    if enclave_id is not None:
        options["enclave-id"] = enclave_id
    if measurement is not None:
        options["measurement"] = measurement
    if key_file is not None:
        options["key-file"] = key_file
    args = None
    command = _build_aitbc_cli_command(
        "tee",
        subcommand=["attest"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "tee",
            subcommand=["attest"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_tee_keygen(
    key_file: Annotated[str, Field(description="Path to create (or read) a stable signing key at.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Generate a new TEE enclave signing key.."""
    options: dict[str, Any] = {}
    if key_file is not None:
        options["key-file"] = key_file
    args = None
    command = _build_aitbc_cli_command(
        "tee",
        subcommand=["keygen"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "tee",
            subcommand=["keygen"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_tee_launch(
    enclave_id: Annotated[str, Field(description="The Enclave-id.")],
    image: Annotated[str | None, Field(description="Enclave image identifier")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Launch a TEE enclave with a given image.."""
    options: dict[str, Any] = {}
    if enclave_id is not None:
        options["enclave-id"] = enclave_id
    if image is not None:
        options["image"] = image
    args = None
    command = _build_aitbc_cli_command(
        "tee",
        subcommand=["launch"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "tee",
            subcommand=["launch"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_tee_register(
    enclave_id: Annotated[str, Field(description="The Enclave-id.")],
    public_key: Annotated[str | None, Field(description="Base64-encoded Ed25519 public key for the enclave")],
    agent_id: Annotated[
        str | None,
        Field(
            description="Deprecated: ownership is derived from your authenticated identity, this flag is ignored server-side"
        ),
    ],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Register a TEE enclave with its public key and optional agent ID.."""
    options: dict[str, Any] = {}
    if enclave_id is not None:
        options["enclave-id"] = enclave_id
    if public_key is not None:
        options["public-key"] = public_key
    if agent_id is not None:
        options["agent-id"] = agent_id
    args = None
    command = _build_aitbc_cli_command(
        "tee",
        subcommand=["register"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "tee",
            subcommand=["register"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_tee_status(
    enclave_id: Annotated[str, Field(description="The Enclave-id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Check the status of a TEE enclave.."""
    options: dict[str, Any] = {}
    if enclave_id is not None:
        options["enclave-id"] = enclave_id
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "tee",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_tee_verify(
    quote: Annotated[str | None, Field(description="Base64-encoded attestation quote")],
    attestation_id: Annotated[str | None, Field(description="Stored TEE attestation ID to verify")],
    job_id: Annotated[str | None, Field(description="Job whose tee_attestation_id will be verified")],
    measurement: Annotated[str | None, Field(description="Expected measurement to verify against")],
    zk_proof: Annotated[str | None, Field(description="Optional ZK proof identifier for dual verification")],
    mode: Annotated[Literal["zk_only", "tee_only", "both"] | None, Field(description="Verification mode")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Verify a TEE quote, attestation, or zero-knowledge proof.."""
    options: dict[str, Any] = {}
    if quote is not None:
        options["quote"] = quote
    if attestation_id is not None:
        options["attestation-id"] = attestation_id
    if job_id is not None:
        options["job-id"] = job_id
    if measurement is not None:
        options["measurement"] = measurement
    if zk_proof is not None:
        options["zk-proof"] = zk_proof
    if mode is not None:
        options["mode"] = mode
    args = None
    command = _build_aitbc_cli_command(
        "tee",
        subcommand=["verify"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "tee",
            subcommand=["verify"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
