# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 10 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_download(
    cid: Annotated[str | None, Field(description="The Cid.")],
    wait: Annotated[bool | None, Field(description="Wait for the CID to become available on the network")],
    access_key: Annotated[str | None, Field(description="Rental access key (looks up CID from hub)")],
    access_secret: Annotated[str | None, Field(description="Rental access secret")],
    rental_id: Annotated[str | None, Field(description="Local rental ID (looks up CID and validates access)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Download content by CID, access key, or rental ID and optionally write it to a file.."""
    options: dict[str, Any] = {}
    if cid is not None:
        options["cid"] = cid
    if wait:
        options["wait"] = None
    if access_key is not None:
        options["access-key"] = access_key
    if access_secret is not None:
        options["access-secret"] = access_secret
    if rental_id is not None:
        options["rental-id"] = rental_id
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["download"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["download"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_host(
    offer_id_or_plugin_id: Annotated[str, Field(description="The Offer id or plugin id.")],
    cid_or_file: Annotated[str, Field(description="The Cid or file.")],
    days: Annotated[int | None, Field(description="Rental duration in days")],
    wallet_name: Annotated[str | None, Field(description="Wallet to pay for the rental")],
    wallet_path: Annotated[str | None, Field(description="Direct wallet file path")],
    password: Annotated[str | None, Field(description="Wallet password")],
    pin: Annotated[bool | None, Field(description="Pin the CID after paying the rental")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Host IPFS content for a marketplace offer or plugin for a number of days.."""
    options: dict[str, Any] = {}
    if offer_id_or_plugin_id is not None:
        options["offer-id-or-plugin-id"] = offer_id_or_plugin_id
    if cid_or_file is not None:
        options["cid-or-file"] = cid_or_file
    if days is not None:
        options["days"] = days
    if wallet_name is not None:
        options["wallet"] = wallet_name
    if wallet_path is not None:
        options["wallet-path"] = wallet_path
    if password is not None:
        options["password"] = password
    if pin:
        options["pin"] = None
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["host"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["host"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_island_subscribe(
    wallet_name: Annotated[str, Field(description="Wallet name to pay from")],
    to_address: Annotated[str, Field(description="Island treasury / recipient address")],
    island_id: Annotated[str, Field(description="Island identifier (e.g. ait-hub.aitbc.bubuit.net-island)")],
    amount: Annotated[str, Field(description="Payment amount in AIT")],
    duration: Annotated[int | None, Field(description="Subscription duration in blocks (default 1000)")],
    quota: Annotated[int | None, Field(description="Quota in bytes (default 1 GiB)")],
    fee: Annotated[str | None, Field(description="Transaction fee in AIT")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="File containing wallet password")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Subscribe to a private island IPFS network.."""
    options: dict[str, Any] = {}
    if wallet_name is not None:
        options["wallet"] = wallet_name
    if to_address is not None:
        options["to"] = to_address
    if island_id is not None:
        options["island-id"] = island_id
    if duration is not None:
        options["duration"] = duration
    if quota is not None:
        options["quota"] = quota
    if amount is not None:
        options["amount"] = amount
    if fee is not None:
        options["fee"] = fee
    if password is not None:
        options["password"] = password
    if password_file is not None:
        options["password-file"] = password_file
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["island", "subscribe"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["island", "subscribe"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_island_swarm_key(
    wallet_name: Annotated[str, Field(description="Wallet name whose address is subscribed")],
    island_id: Annotated[str, Field(description="Island identifier")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator API base URL")],
    chain_id: Annotated[str | None, Field(description="Blockchain chain ID (auto-detected from RPC if omitted)")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL for chain ID auto-detection")],
    api_key: Annotated[
        str | None, Field(description="Coordinator API key (default from config / AITBC_API_KEY / MINER_API_KEYS)")
    ],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="File containing wallet password")],
    bootstrap: Annotated[bool | None, Field(description="Also print a bootstrap multiaddr for the hub island daemon")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Request the swarm key for a subscribed island IPFS network.."""
    options: dict[str, Any] = {}
    if wallet_name is not None:
        options["wallet"] = wallet_name
    if island_id is not None:
        options["island-id"] = island_id
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    if chain_id is not None:
        options["chain-id"] = chain_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    if api_key is not None:
        options["api-key"] = api_key
    if password is not None:
        options["password"] = password
    if password_file is not None:
        options["password-file"] = password_file
    if bootstrap:
        options["bootstrap"] = None
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["island", "swarm-key"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["island", "swarm-key"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_ipfs_list(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List uploaded and pinned IPFS items.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "ipfs",
        subcommand=["list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_pin(
    cid: Annotated[str, Field(description="The Cid.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Pin content by CID on the local Kubo daemon or filesystem index.."""
    options: dict[str, Any] = {}
    if cid is not None:
        options["cid"] = cid
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["pin"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["pin"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_rentals(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List all active IPFS rentals and their details.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["rentals"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["rentals"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_token(
    rental_id: Annotated[str, Field(description="The Rental id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get an access token for an IPFS rental.."""
    options: dict[str, Any] = {}
    if rental_id is not None:
        options["rental-id"] = rental_id
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["token"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["token"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_unpin(
    rental_id: Annotated[str, Field(description="The Rental id.")],
    refund: Annotated[bool | None, Field(description="Refund the escrow for this rental")],
    reason: Annotated[str | None, Field(description="Reason for refund")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Unpin a CID and end an IPFS rental with an optional refund.."""
    options: dict[str, Any] = {}
    if rental_id is not None:
        options["rental-id"] = rental_id
    if refund:
        options["refund"] = None
    if reason is not None:
        options["reason"] = reason
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["unpin"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["unpin"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ipfs_upload(
    file: Annotated[str, Field(description="File to upload")],
    pin: Annotated[bool | None, Field(description="Pin uploaded content")],
    name: Annotated[str | None, Field(description="Human-readable name for the upload")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Upload a file to IPFS and return its CID.."""
    options: dict[str, Any] = {}
    if file is not None:
        options["file"] = file
    if pin:
        options["pin"] = None
    if name is not None:
        options["name"] = name
    args = None
    command = _build_aitbc_cli_command(
        "ipfs",
        subcommand=["upload"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ipfs",
            subcommand=["upload"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
