# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 5 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _collect_options,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_crosschain_bridge(
    source_chain: Annotated[str, Field(description="Source chain ID")],
    target_chain: Annotated[str, Field(description="Target chain ID")],
    token: Annotated[str, Field(description="Token to bridge")],
    amount: Annotated[str, Field(description="Amount to bridge (AIT)")],
    recipient: Annotated[str | None, Field(description="Recipient address on the target chain (defaults to the sender)")],
    wallet: Annotated[str | None, Field(description="Wallet name or file path for signing")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="File containing wallet password")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL (source-chain producer)")],
    wait: Annotated[bool | None, Field(description="Poll status until the transfer reaches a terminal state")],
    timeout_opt: Annotated[int | None, Field(description="Seconds to wait with --wait (default 300)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Bridge tokens to a target chain via a real signed bridge lock.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"wait": "wait"},
        values={
            "source_chain": "source-chain",
            "target_chain": "target-chain",
            "token": "token",
            "amount": "amount",
            "recipient": "recipient",
            "wallet": "wallet",
            "password": "password",
            "password_file": "password-file",
            "rpc_url": "rpc-url",
            "timeout_opt": "timeout",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "crosschain",
        subcommand=["bridge"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "crosschain",
            subcommand=["bridge"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_crosschain_bridge_status(
    bridge_id: Annotated[str, Field(description="The bridge/transfer ID.")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    wait: Annotated[bool | None, Field(description="Poll status until a terminal state")],
    timeout_opt: Annotated[int | None, Field(description="Seconds to wait with --wait")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Check the real status of a cross-chain bridge transfer.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"wait": "wait"},
        values={"bridge_id": "transfer-id", "rpc_url": "rpc-url", "timeout_opt": "timeout"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "crosschain",
        subcommand=["bridge-status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "crosschain",
            subcommand=["bridge-status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_crosschain_confirm(
    transfer_id: Annotated[str, Field(description="The bridge transfer ID")],
    source_chain: Annotated[str | None, Field(description="Source chain ID (defaults to the node's chain)")],
    wallet: Annotated[str | None, Field(description="Wallet name or file path for signing the confirm")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="File containing wallet password")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Confirm a pending bridge transfer with its real Merkle proof.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={
            "transfer_id": "transfer-id",
            "source_chain": "source-chain",
            "wallet": "wallet",
            "password": "password",
            "password_file": "password-file",
            "rpc_url": "rpc-url",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "crosschain",
        subcommand=["confirm"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "crosschain",
            subcommand=["confirm"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_crosschain_stats(
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show cross-chain trading statistics from real persisted records.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"rpc_url": "rpc-url"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "crosschain",
        subcommand=["stats"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_crosschain_swap(
    from_chain: Annotated[str, Field(description="Source chain ID")],
    to_chain: Annotated[str, Field(description="Target chain ID")],
    from_token: Annotated[str, Field(description="Source token symbol")],
    to_token: Annotated[str, Field(description="Target token symbol")],
    amount: Annotated[str, Field(description="Amount to swap (AIT)")],
    min_amount: Annotated[str | None, Field(description="Minimum amount to receive on target chain (AIT)")],
    slippage: Annotated[float | None, Field(description="Slippage tolerance (0-0.1)")],
    recipient: Annotated[str | None, Field(description="Recipient address on the target chain (defaults to the sender)")],
    wallet: Annotated[str | None, Field(description="Wallet name or file path for signing")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="File containing wallet password")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL (source-chain producer)")],
    wait: Annotated[bool | None, Field(description="Poll status until the transfer reaches a terminal state")],
    timeout_opt: Annotated[int | None, Field(description="Seconds to wait with --wait (default 300)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create a cross-chain token swap via a real signed bridge lock.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"wait": "wait"},
        values={
            "from_chain": "from-chain",
            "to_chain": "to-chain",
            "from_token": "from-token",
            "to_token": "to-token",
            "amount": "amount",
            "min_amount": "min-amount",
            "slippage": "slippage",
            "recipient": "recipient",
            "wallet": "wallet",
            "password": "password",
            "password_file": "password-file",
            "rpc_url": "rpc-url",
            "timeout_opt": "timeout",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "crosschain",
        subcommand=["swap"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "crosschain",
            subcommand=["swap"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
