# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 1 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_restart(
    dry_run_opt: Annotated[bool | None, Field(description="Show which systemctl commands would run without running them")],
    role_opt: Annotated[
        Literal["hub", "shop", "follower", "customer"] | None,
        Field(description="Override the node role (default: auto-detect from /etc/aitbc)"),
    ],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Restart all AITBC services for the current (or selected) role."""
    options: dict[str, Any] = {}
    if dry_run_opt:
        options["dry-run"] = None
    if role_opt is not None:
        options["role"] = role_opt
    args = None
    command = _build_aitbc_cli_command(
        "restart",
        subcommand=None,
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "restart",
            subcommand=None,
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
