# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 17 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_attest(
    private_key: Annotated[str, Field(description="Validator private key hex to sign with")],
    header_file: Annotated[str | None, Field(description="JSON file with a block header to attest")],
    source_rpc: Annotated[str | None, Field(description="RPC URL to fetch the block from (alternative to --header-file)")],
    height: Annotated[int | None, Field(description="Block height to fetch from source")],
    chain_id: Annotated[str | None, Field(description="Chain ID for the block")],
    proposer: Annotated[str | None, Field(description="Proposer/validator address (defaults to derived address)")],
    target_rpc: Annotated[str | None, Field(description="RPC URL to store the attested header on")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Sign a block header as a bridge validator and store it as a bridge header.."""
    options: dict[str, Any] = {}
    if header_file is not None:
        options["header-file"] = header_file
    if source_rpc is not None:
        options["source-rpc"] = source_rpc
    if height is not None:
        options["height"] = height
    if chain_id is not None:
        options["chain-id"] = chain_id
    if private_key is not None:
        options["private-key"] = private_key
    if proposer is not None:
        options["proposer"] = proposer
    if target_rpc is not None:
        options["target-rpc"] = target_rpc
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["attest"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["attest"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_bridge_balance(
    chain_id: Annotated[str, Field(description="Chain ID to query balance for")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get the total locked bridge balance for a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "bridge",
        subcommand=["balance"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_confirm(
    transfer_id: Annotated[str, Field(description="Transfer ID to confirm")],
    confirmer: Annotated[str, Field(description="Confirmer address")],
    proof_file: Annotated[str, Field(description="JSON file containing the lock proof")],
    signature: Annotated[str | None, Field(description="Confirmer signature (hex)")],
    confirmer_private_key: Annotated[str | None, Field(description="Private key to sign the confirm request")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Confirm and release a cross-chain bridge transfer using a proof file.."""
    options: dict[str, Any] = {}
    if transfer_id is not None:
        options["transfer-id"] = transfer_id
    if confirmer is not None:
        options["confirmer"] = confirmer
    if signature is not None:
        options["signature"] = signature
    if confirmer_private_key is not None:
        options["confirmer-private-key"] = confirmer_private_key
    if proof_file is not None:
        options["proof-file"] = proof_file
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["confirm"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["confirm"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_bridge_health(
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Check the bridge service health and connected node status.."""
    options: dict[str, Any] = {}
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "bridge",
        subcommand=["health"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_ingest_header(
    source_rpc: Annotated[str | None, Field(description="RPC URL of the source chain node")],
    target_rpc: Annotated[str | None, Field(description="RPC URL to store the header on (defaults to localhost)")],
    height: Annotated[int | None, Field(description="Block height to ingest (default: latest)")],
    chain_id: Annotated[str | None, Field(description="Source chain ID (default: source node's default)")],
    re_sign: Annotated[bool | None, Field(description="Replace the source signature with a local validator signature")],
    private_key: Annotated[str | None, Field(description="Private key hex for re-signing (requires --re-sign)")],
    proposer: Annotated[
        str | None, Field(description="Proposer address for the new signature (defaults to address of --private-key)")
    ],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Fetch a block header from a source node and store it as a bridge header.."""
    options: dict[str, Any] = {}
    if source_rpc is not None:
        options["source-rpc"] = source_rpc
    if target_rpc is not None:
        options["target-rpc"] = target_rpc
    if height is not None:
        options["height"] = height
    if chain_id is not None:
        options["chain-id"] = chain_id
    if re_sign:
        options["re-sign"] = None
    if private_key is not None:
        options["private-key"] = private_key
    if proposer is not None:
        options["proposer"] = proposer
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["ingest-header"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["ingest-header"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_lock(
    target_chain: Annotated[str, Field(description="Target chain ID for the transfer")],
    sender: Annotated[str, Field(description="Sender address (source chain)")],
    recipient: Annotated[str, Field(description="Recipient address (target chain)")],
    amount: Annotated[int, Field(description="Amount to bridge (in compute-units)")],
    asset: Annotated[str | None, Field(description="Asset type (default: native)")],
    source_chain: Annotated[str | None, Field(description="Source chain ID (defaults to node's chain)")],
    signature: Annotated[str | None, Field(description="Sender signature authorizing the lock (hex)")],
    wallet_name: Annotated[str | None, Field(description="Wallet to sign the lock with")],
    wallet_password: Annotated[str | None, Field(description="Password if the wallet is encrypted")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Lock funds for a cross-chain bridge transfer.."""
    options: dict[str, Any] = {}
    if target_chain is not None:
        options["target-chain"] = target_chain
    if sender is not None:
        options["sender"] = sender
    if recipient is not None:
        options["recipient"] = recipient
    if amount is not None:
        options["amount"] = amount
    if asset is not None:
        options["asset"] = asset
    if source_chain is not None:
        options["source-chain"] = source_chain
    if signature is not None:
        options["signature"] = signature
    if wallet_name is not None:
        options["wallet-name"] = wallet_name
    if wallet_password is not None:
        options["wallet-password"] = wallet_password
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["lock"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["lock"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_oracle_status(
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get bridge oracle and verification status.."""
    options: dict[str, Any] = {}
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["oracle-status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["oracle-status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_pending(
    chain_id: Annotated[str | None, Field(description="Filter by chain ID")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List pending bridge transfers, optionally filtered by chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["pending"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["pending"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_proof(
    transfer_id: Annotated[str, Field(description="Transfer ID.")],
    source_chain: Annotated[str | None, Field(description="Source chain ID (defaults to node's chain)")],
    block_height: Annotated[int | None, Field(description="Block height to anchor the proof")],
    block_hash: Annotated[str | None, Field(description="Block hash to anchor the proof")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Build a Merkle proof for a locked bridge transfer.."""
    options: dict[str, Any] = {}
    if transfer_id is not None:
        options["transfer-id"] = transfer_id
    if source_chain is not None:
        options["source-chain"] = source_chain
    if block_height is not None:
        options["block-height"] = block_height
    if block_hash is not None:
        options["block-hash"] = block_hash
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["proof"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["proof"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_register_validator(
    chain_id: Annotated[str, Field(description="Chain ID the validator serves")],
    address: Annotated[str, Field(description="Validator's checksum address (0x...)")],
    public_key: Annotated[str, Field(description="Validator's secp256k1 public key hex (0x...)")],
    private_key: Annotated[str, Field(description="Validator's private key hex (for signing the registration request)")],
    admin_private_key: Annotated[
        str | None, Field(description="Bridge admin private key hex (required when bridge_release_enabled=true)")
    ],
    admin_address: Annotated[str | None, Field(description="Bridge admin address (defaults to address of admin-private-key)")],
    epoch: Annotated[int | None, Field(description="Validator set epoch number (default: 0)")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Register a bridge validator for multi-sig operations on a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if address is not None:
        options["address"] = address
    if public_key is not None:
        options["public-key"] = public_key
    if private_key is not None:
        options["private-key"] = private_key
    if admin_private_key is not None:
        options["admin-private-key"] = admin_private_key
    if admin_address is not None:
        options["admin-address"] = admin_address
    if epoch is not None:
        options["epoch"] = epoch
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["register-validator"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["register-validator"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_security_status(
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get bridge security status, multi-sig configuration, and threshold.."""
    options: dict[str, Any] = {}
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["security-status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["security-status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_sign_proof(
    proof_file: Annotated[str, Field(description="Unsigned proof JSON file")],
    private_key: Annotated[
        list[str],
        Field(description="Private key hex to sign with (use multiple times for multi-sig; first becomes proposer_signature)"),
    ],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Sign a bridge proof with one or more validator private keys.."""
    options: dict[str, Any] = {}
    if proof_file is not None:
        options["proof-file"] = proof_file
    if private_key is not None:
        options["private-key"] = private_key
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["sign-proof"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["sign-proof"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_start(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Start the blockchain event bridge service.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["start"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["start"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_bridge_status(
    transfer_id: Annotated[str | None, Field(description="Transfer ID.")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get bridge service status or a specific transfer status.."""
    options: dict[str, Any] = {}
    if transfer_id is not None:
        options["transfer-id"] = transfer_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "bridge",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_stop(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Stop the blockchain event bridge service.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["stop"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["stop"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_store_header(
    proof_file: Annotated[str, Field(description="Signed proof JSON file")],
    admin_private_key: Annotated[str, Field(description="Private key of a configured bridge admin")],
    admin_address: Annotated[str | None, Field(description="Admin address (defaults to address of admin-private-key)")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL of the target node")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Store a bridge block header on the target node from a signed proof.."""
    options: dict[str, Any] = {}
    if proof_file is not None:
        options["proof-file"] = proof_file
    if admin_private_key is not None:
        options["admin-private-key"] = admin_private_key
    if admin_address is not None:
        options["admin-address"] = admin_address
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["store-header"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["store-header"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_bridge_unlock(
    transfer_id: Annotated[str, Field(description="Transfer ID to refund")],
    sender: Annotated[str, Field(description="Original sender address")],
    signature: Annotated[str, Field(description="Sender signature authorizing the unlock")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Refund or cancel a pending bridge transfer.."""
    options: dict[str, Any] = {}
    if transfer_id is not None:
        options["transfer-id"] = transfer_id
    if sender is not None:
        options["sender"] = sender
    if signature is not None:
        options["signature"] = signature
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    command = _build_aitbc_cli_command(
        "bridge",
        subcommand=["unlock"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "bridge",
            subcommand=["unlock"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
