# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 8 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from decimal import Decimal

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _collect_options,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_simulate_ai_jobs(
    jobs: Annotated[int | None, Field(description="Number of AI jobs to simulate")],
    models: Annotated[str | None, Field(description="Available models (comma-separated)")],
    duration_range: Annotated[str | None, Field(description="Job duration range in seconds (min-max)")],
    delay: Annotated[float | None, Field(description="Delay between job status checks (seconds)")],
    seed: Annotated[int | None, Field(description="Seed for deterministic simulation (default: live)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Simulate AI job submissions and completions.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"jobs": "jobs", "models": "models", "duration_range": "duration-range", "delay": "delay", "seed": "seed"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "simulate",
        subcommand=["ai-jobs"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "simulate",
            subcommand=["ai-jobs"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_simulate_blockchain(
    blocks: Annotated[int | None, Field(description="Number of blocks to simulate")],
    transactions: Annotated[int | None, Field(description="Number of transactions per block")],
    delay: Annotated[float | None, Field(description="Delay between blocks (seconds)")],
    seed: Annotated[int | None, Field(description="Seed for deterministic simulation (default: live)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Simulate blockchain block generation and transactions.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"blocks": "blocks", "transactions": "transactions", "delay": "delay", "seed": "seed"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "simulate",
        subcommand=["blockchain"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "simulate",
            subcommand=["blockchain"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_simulate_network(
    nodes: Annotated[int | None, Field(description="Number of nodes to simulate")],
    network_delay: Annotated[float | None, Field(description="Network delay in seconds")],
    failure_rate: Annotated[float | None, Field(description="Node failure rate (0.0-1.0)")],
    seed: Annotated[int | None, Field(description="Seed for deterministic simulation (default: live)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Simulate network nodes, delays, and failure rates.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"nodes": "nodes", "network_delay": "network-delay", "failure_rate": "failure-rate", "seed": "seed"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "simulate",
        subcommand=["network"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_simulate_price(
    price: Annotated[Decimal | None, Field(description="Starting AIT price")],
    volatility: Annotated[float | None, Field(description="Price volatility (0.0-1.0)")],
    timesteps: Annotated[int | None, Field(description="Number of timesteps to simulate")],
    delay: Annotated[float | None, Field(description="Delay between timesteps (seconds)")],
    seed: Annotated[int | None, Field(description="Seed for deterministic simulation (default: live)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Simulate AIT price movements with configurable volatility.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"price": "price", "volatility": "volatility", "timesteps": "timesteps", "delay": "delay", "seed": "seed"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "simulate",
        subcommand=["price"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "simulate",
            subcommand=["price"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_simulate_result(
    simulation_id: Annotated[str, Field(description="The Simulation id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get the results of a completed simulation.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"simulation_id": "simulation-id"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "simulate",
        subcommand=["result"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "simulate",
            subcommand=["result"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_simulate_run(
    scenario: Annotated[str, Field(description="The Scenario.")],
    params: Annotated[str | None, Field(description="Simulation parameters (JSON string)")],
    async_run: Annotated[bool | None, Field(description="Run simulation asynchronously")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Run a named simulation scenario with optional parameters.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"async_run": "async-run"},
        values={"scenario": "scenario", "params": "params"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "simulate",
        subcommand=["run"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "simulate",
            subcommand=["run"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_simulate_status(
    simulation_id: Annotated[str, Field(description="The Simulation id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get the status of a running simulation.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"simulation_id": "simulation-id"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "simulate",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_simulate_wallets(
    wallets: Annotated[int | None, Field(description="Number of wallets to simulate")],
    balance: Annotated[Decimal | None, Field(description="Initial balance for each wallet")],
    transactions: Annotated[int | None, Field(description="Number of transactions to simulate")],
    amount_range: Annotated[str | None, Field(description="Transaction amount range (min-max)")],
    seed: Annotated[int | None, Field(description="Seed for deterministic simulation (default: live)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Simulate wallet creation and transactions with configurable balance.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={
            "wallets": "wallets",
            "balance": "balance",
            "transactions": "transactions",
            "amount_range": "amount-range",
            "seed": "seed",
        },
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "simulate",
        subcommand=["wallets"],
        args=args,
        options=options,
        timeout=timeout,
    )
