# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 7 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _collect_options,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_exchange_add_liquidity(
    pair: Annotated[str, Field(description="Trading pair symbol (e.g., AITBC/ETH)")],
    amount: Annotated[str, Field(description="Liquidity amount")],
    side: Annotated[Literal["buy", "sell"] | None, Field(description="Side to provide liquidity")],
    exchange: Annotated[str | None, Field(description="Exchange name")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Add liquidity to a trading pair on the specified side.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"pair": "pair", "amount": "amount", "side": "side", "exchange": "exchange"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "exchange",
        subcommand=["add-liquidity"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "exchange",
            subcommand=["add-liquidity"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_exchange_create_pair(
    base_asset: Annotated[str, Field(description="Base asset symbol (e.g., AITBC)")],
    quote_asset: Annotated[str, Field(description="Quote asset symbol (e.g., ETH)")],
    exchange: Annotated[str, Field(description="Exchange name")],
    min_order_size: Annotated[float | None, Field(description="Minimum order size")],
    price_precision: Annotated[int | None, Field(description="Price precision")],
    quantity_precision: Annotated[int | None, Field(description="Quantity precision")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create a new trading pair on a registered exchange with precision and minimum order size.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={
            "base_asset": "base-asset",
            "quote_asset": "quote-asset",
            "exchange": "exchange",
            "min_order_size": "min-order-size",
            "price_precision": "price-precision",
            "quantity_precision": "quantity-precision",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "exchange",
        subcommand=["create-pair"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "exchange",
            subcommand=["create-pair"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_exchange_list(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List all registered exchanges and their trading pairs.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "exchange",
        subcommand=["list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_exchange_monitor(
    pair: Annotated[str | None, Field(description="Trading pair symbol (e.g., AITBC/ETH)")],
    exchange: Annotated[str | None, Field(description="Exchange name")],
    real_time: Annotated[bool | None, Field(description="Enable real-time monitoring")],
    interval: Annotated[int | None, Field(description="Update interval in seconds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Monitor exchange trading activity across registered pairs and exchanges.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"real_time": "real-time"},
        values={"pair": "pair", "exchange": "exchange", "interval": "interval"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "exchange",
        subcommand=["monitor"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_exchange_register(
    name: Annotated[str, Field(description="Exchange name (e.g., Binance, Coinbase, Kraken)")],
    api_key: Annotated[str, Field(description="Exchange API key")],
    secret_key: Annotated[str | None, Field(description="Exchange API secret key")],
    sandbox: Annotated[bool | None, Field(description="Use sandbox/testnet environment")],
    description: Annotated[str | None, Field(description="Exchange description")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Register a new exchange integration with API credentials and optional sandbox mode.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"sandbox": "sandbox"},
        values={"name": "name", "api_key": "api-key", "secret_key": "secret-key", "description": "description"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "exchange",
        subcommand=["register"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "exchange",
            subcommand=["register"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_exchange_start_trading(
    pair: Annotated[str, Field(description="Trading pair symbol (e.g., AITBC/ETH)")],
    price: Annotated[str | None, Field(description="Initial price for the pair")],
    base_liquidity: Annotated[float | None, Field(description="Base asset liquidity amount")],
    quote_liquidity: Annotated[float | None, Field(description="Quote asset liquidity amount")],
    exchange: Annotated[str | None, Field(description="Exchange name (if not specified, uses first available)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Start trading for a specific pair with optional initial price and liquidity.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={
            "pair": "pair",
            "price": "price",
            "base_liquidity": "base-liquidity",
            "quote_liquidity": "quote-liquidity",
            "exchange": "exchange",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "exchange",
        subcommand=["start-trading"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "exchange",
            subcommand=["start-trading"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_exchange_status(
    exchange_name: Annotated[str, Field(description="The Exchange name.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get the status and configuration of a specific registered exchange.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"exchange_name": "exchange-name"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "exchange",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )
