# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 4 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_analytics_alerts(
    severity: Annotated[Literal["all", "critical", "warning"] | None, Field(description="Alert severity filter")],
    hours: Annotated[int | None, Field(description="Time range in hours")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """View performance alerts filtered by severity and time range.."""
    options: dict[str, Any] = {}
    if severity is not None:
        options["severity"] = severity
    if hours is not None:
        options["hours"] = hours
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "analytics",
        subcommand=["alerts"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_analytics_monitor(
    realtime: Annotated[bool | None, Field(description="Real-time monitoring")],
    interval: Annotated[int | None, Field(description="Update interval in seconds")],
    chain_id: Annotated[str | None, Field(description="Monitor specific chain")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Monitor chain performance in real time or take a single snapshot.."""
    options: dict[str, Any] = {}
    if realtime:
        options["realtime"] = None
    if interval is not None:
        options["interval"] = interval
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "analytics",
        subcommand=["monitor"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_analytics_optimize(
    chain_id: Annotated[str | None, Field(description="Specific chain ID for recommendations")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get optimization recommendations for one chain or all chains.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "analytics",
        subcommand=["optimize"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "analytics",
            subcommand=["optimize"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_analytics_predict(
    chain_id: Annotated[str | None, Field(description="Specific chain ID for predictions")],
    hours: Annotated[int | None, Field(description="Prediction time horizon in hours")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Predict future chain performance for a single chain or all chains.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if hours is not None:
        options["hours"] = hours
    args = None
    command = _build_aitbc_cli_command(
        "analytics",
        subcommand=["predict"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "analytics",
            subcommand=["predict"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
