# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 11 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from decimal import Decimal

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_accept(
    job_id: Annotated[str, Field(description="Job ID to accept")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Accept a completed AI job and release the escrowed payment.."""
    options: dict[str, Any] = {}
    if job_id is not None:
        options["job-id"] = job_id
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["accept"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["accept"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_cancel(
    job_id: Annotated[str, Field(description="Job ID")],
    wallet: Annotated[str | None, Field(description="Wallet name (optional)")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="Password file")],
    refund: Annotated[bool | None, Field(description="Also refund the escrowed payment after cancel")],
    reason: Annotated[str | None, Field(description="Reason for refund")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Cancel an AI job and optionally refund the payment to the customer.."""
    options: dict[str, Any] = {}
    if job_id is not None:
        options["job-id"] = job_id
    if wallet is not None:
        options["wallet"] = wallet
    if password is not None:
        options["password"] = password
    if password_file is not None:
        options["password-file"] = password_file
    if refund:
        options["refund"] = None
    if reason is not None:
        options["reason"] = reason
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["cancel"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["cancel"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_ai_jobs(
    limit: Annotated[int | None, Field(description="Limit results")],
    status: Annotated[str | None, Field(description="Filter by status")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List AI jobs from the coordinator with optional status and limit filters.."""
    options: dict[str, Any] = {}
    if limit is not None:
        options["limit"] = limit
    if status is not None:
        options["status"] = status
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "ai",
        subcommand=["jobs"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_pay(
    job_id: Annotated[str, Field(description="Job ID to pay for")],
    wallet: Annotated[str, Field(description="Wallet name to sign the escrow lock")],
    buyer_address: Annotated[str | None, Field(description="Override buyer/customer address")],
    provider_address: Annotated[str | None, Field(description="Override provider address")],
    offer_id: Annotated[str | None, Field(description="Marketplace offer this job is bought against")],
    offer_quantity: Annotated[str | None, Field(description="How many of the offer's price units to buy")],
    currency: Annotated[str | None, Field(description="Payment currency (default: AITBC)")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    rpc_url: Annotated[str | None, Field(description="Blockchain RPC URL")],
    chain_id: Annotated[str | None, Field(description="Chain ID")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="Password file")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create an escrow payment for an existing AI job.."""
    options: dict[str, Any] = {}
    if job_id is not None:
        options["job-id"] = job_id
    if wallet is not None:
        options["wallet"] = wallet
    if buyer_address is not None:
        options["buyer-address"] = buyer_address
    if provider_address is not None:
        options["provider-address"] = provider_address
    if offer_id is not None:
        options["offer-id"] = offer_id
    if offer_quantity is not None:
        options["offer-quantity"] = offer_quantity
    if currency is not None:
        options["currency"] = currency
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    if chain_id is not None:
        options["chain-id"] = chain_id
    if password is not None:
        options["password"] = password
    if password_file is not None:
        options["password-file"] = password_file
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["pay"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["pay"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_refund(
    job_id: Annotated[str, Field(description="Job ID to refund")],
    reason: Annotated[str | None, Field(description="Reason for refund")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Refund an escrowed payment for a failed or cancelled AI job.."""
    options: dict[str, Any] = {}
    if job_id is not None:
        options["job-id"] = job_id
    if reason is not None:
        options["reason"] = reason
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["refund"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["refund"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_refund_sweep(
    limit: Annotated[int | None, Field(description="Maximum completed jobs to inspect")],
    reason: Annotated[str | None, Field(description="Reason for refund")],
    dry_run_opt: Annotated[bool | None, Field(description="Count candidates without refunding")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Refund all client-owned AI jobs stuck in an incomplete state.."""
    options: dict[str, Any] = {}
    if limit is not None:
        options["limit"] = limit
    if reason is not None:
        options["reason"] = reason
    if dry_run_opt:
        options["dry-run"] = None
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["refund-sweep"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["refund-sweep"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_results(
    job_id: Annotated[str | None, Field(description="Job ID")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Show the results of a completed AI job by job ID.."""
    options: dict[str, Any] = {}
    if job_id is not None:
        options["job-id"] = job_id
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["results"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["results"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_service_test(
    name: Annotated[str | None, Field(description="Service name")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Test an AI service endpoint by service name.."""
    options: dict[str, Any] = {}
    if name is not None:
        options["name"] = name
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["service", "test"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["service", "test"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_ai_stats(
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show aggregate AI service statistics from the coordinator.."""
    options: dict[str, Any] = {}
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "ai",
        subcommand=["stats"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_ai_status(
    job_id: Annotated[str | None, Field(description="Job ID")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show the current status of an AI job by job ID.."""
    options: dict[str, Any] = {}
    if job_id is not None:
        options["job-id"] = job_id
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "ai",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_ai_submit(
    wallet: Annotated[str | None, Field(description="Wallet name")],
    job_type: Annotated[str | None, Field(description="Job type")],
    prompt: Annotated[str | None, Field(description="Job prompt")],
    model: Annotated[str | None, Field(description="Ollama model to use")],
    payment: Annotated[Decimal | None, Field(description="Payment amount")],
    currency: Annotated[str | None, Field(description="Payment currency (default: AITBC)")],
    buyer_address: Annotated[str | None, Field(description="Customer wallet address for escrow")],
    provider_address: Annotated[str | None, Field(description="Provider wallet address for escrow")],
    offer_id: Annotated[str | None, Field(description="Marketplace offer this job is bought against")],
    offer_quantity: Annotated[str | None, Field(description="How many of the offer's price units to buy (default: 1)")],
    acceptance_window: Annotated[
        int | None, Field(description="Seconds after completion before payment auto-releases (default: 0)")
    ],
    min_reputation: Annotated[
        float | None, Field(description="Minimum provider reputation score (0-1) required for this job")
    ],
    zk_proof_required: Annotated[bool | None, Field(description="Require a ZK receipt proof before escrow release")],
    tee_attestation_required: Annotated[bool | None, Field(description="Require a TEE attestation before escrow release")],
    tee_enclave_id: Annotated[str | None, Field(description="Required TEE enclave identity")],
    confidential: Annotated[bool | None, Field(description="Mark this job as confidential (requires a TEE attestation)")],
    enclave_measurement: Annotated[str | None, Field(description="Required enclave measurement for a confidential job")],
    auto_reinvest_pct: Annotated[
        float | None, Field(description="Percentage of released payment to auto-stake as reinvestment")
    ],
    bond_required: Annotated[bool | None, Field(description="Require the provider to have an active performance bond")],
    min_bond_amount: Annotated[Decimal | None, Field(description="Minimum bond amount required for provider eligibility")],
    deterministic_decoding: Annotated[
        bool | None, Field(description="Use deterministic decoding for reproducible verification")
    ],
    decode_seed: Annotated[int | None, Field(description="Seed for deterministic decoding (auto-assigned if unset)")],
    input_url: Annotated[str | None, Field(description="Input URL or path for transcribe/reencode jobs")],
    classification: Annotated[str | None, Field(description="Data classification label (e.g. public, pii, phi)")],
    compliance_framework: Annotated[str | None, Field(description="Compliance framework to enforce")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="Password file")],
    chain_id: Annotated[str | None, Field(description="Chain ID")],
    rpc_url: Annotated[str | None, Field(description="RPC URL")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    wait: Annotated[bool | None, Field(description="Wait for the job to reach a terminal state")],
    timeout_opt: Annotated[float | None, Field(description="Maximum seconds to wait for a terminal state (default: 300)")],
    poll_interval: Annotated[float | None, Field(description="Seconds between status polls (default: 5)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Submit a new AI job to the coordinator with a prompt and optional model.."""
    options: dict[str, Any] = {}
    if wallet is not None:
        options["wallet"] = wallet
    if job_type is not None:
        options["type"] = job_type
    if prompt is not None:
        options["prompt"] = prompt
    if model is not None:
        options["model"] = model
    if payment is not None:
        options["payment"] = payment
    if currency is not None:
        options["currency"] = currency
    if buyer_address is not None:
        options["buyer-address"] = buyer_address
    if provider_address is not None:
        options["provider-address"] = provider_address
    if offer_id is not None:
        options["offer-id"] = offer_id
    if offer_quantity is not None:
        options["offer-quantity"] = offer_quantity
    if acceptance_window is not None:
        options["acceptance-window"] = acceptance_window
    if min_reputation is not None:
        options["min-reputation"] = min_reputation
    if zk_proof_required:
        options["zk-proof-required"] = None
    if tee_attestation_required:
        options["tee-attestation-required"] = None
    if tee_enclave_id is not None:
        options["tee-enclave-id"] = tee_enclave_id
    if confidential:
        options["confidential"] = None
    if enclave_measurement is not None:
        options["enclave-measurement"] = enclave_measurement
    if auto_reinvest_pct is not None:
        options["auto-reinvest-pct"] = auto_reinvest_pct
    if bond_required:
        options["bond-required"] = None
    if min_bond_amount is not None:
        options["min-bond-amount"] = min_bond_amount
    if deterministic_decoding:
        options["deterministic-decoding"] = None
    if decode_seed is not None:
        options["decode-seed"] = decode_seed
    if input_url is not None:
        options["input"] = input_url
    if classification is not None:
        options["classification"] = classification
    if compliance_framework is not None:
        options["compliance-framework"] = compliance_framework
    if password is not None:
        options["password"] = password
    if password_file is not None:
        options["password-file"] = password_file
    if chain_id is not None:
        options["chain-id"] = chain_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    if coordinator_url is not None:
        options["coordinator-url"] = coordinator_url
    if wait:
        options["wait"] = None
    if timeout_opt is not None:
        options["timeout"] = timeout_opt
    if poll_interval is not None:
        options["poll-interval"] = poll_interval
    args = None
    command = _build_aitbc_cli_command(
        "ai",
        subcommand=["submit"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "ai",
            subcommand=["submit"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
