# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 6 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _collect_options,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_energy_floor(
    resource_id: Annotated[str, Field(description="Canonical resource ID")],
    gpu_count: Annotated[int, Field(description="Number of GPUs")],
    duration_seconds: Annotated[int, Field(description="Rental duration in seconds")],
    settlement_unit_scale: Annotated[int | None, Field(description="Settlement unit scale")],
    json_output: Annotated[bool | None, Field(description="Output raw JSON")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Compute the on-chain energy floor for given rental terms.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"json_output": "json-output"},
        values={
            "resource_id": "resource-id",
            "gpu_count": "gpu-count",
            "duration_seconds": "duration-seconds",
            "settlement_unit_scale": "settlement-unit-scale",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "energy",
        subcommand=["floor"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "energy",
            subcommand=["floor"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_energy_operator_info(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show the configured energy operator address and signing status.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "energy",
        subcommand=["operator", "info"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_energy_operator_verify(
    quote_file: Annotated[str, Field(description="JSON file containing an energy quote")],
    check_oracle: Annotated[bool | None, Field(description="Also verify against the on-chain IEnergyPricing oracle")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Verify an energy quote's operator signature and freshness.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"check_oracle": "check-oracle"},
        values={"quote_file": "quote-file"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "energy",
        subcommand=["operator", "verify"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "energy",
            subcommand=["operator", "verify"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_energy_provider_profile(
    resource_id: Annotated[str, Field(description="Canonical resource ID")],
    json_output: Annotated[bool | None, Field(description="Output raw JSON")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Read a registered energy profile from the IEnergyPricing contract.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"json_output": "json-output"},
        values={"resource_id": "resource-id"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "energy",
        subcommand=["provider", "profile"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_energy_provider_rate(
    publish: Annotated[bool | None, Field(description="Publish a new rate (requires wallet)")],
    ait_per_eur: Annotated[float | None, Field(description="AIT per EUR rate to publish")],
    observed_at: Annotated[int | None, Field(description="Unix timestamp when the rate was observed")],
    source_kind: Annotated[str | None, Field(description="Rate source kind")],
    wallet: Annotated[str | None, Field(description="Wallet name for signing")],
    wallet_path: Annotated[str | None, Field(description="Direct wallet file path")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="Wallet password file")],
    json_output: Annotated[bool | None, Field(description="Output raw JSON")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Read or publish the AIT/EUR energy rate.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"publish": "publish", "json_output": "json-output"},
        values={
            "ait_per_eur": "ait-per-eur",
            "observed_at": "observed-at",
            "source_kind": "source-kind",
            "wallet": "wallet",
            "wallet_path": "wallet-path",
            "password": "password",
            "password_file": "password-file",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "energy",
        subcommand=["provider", "rate"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "energy",
            subcommand=["provider", "rate"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_energy_provider_register(
    resource_id: Annotated[str, Field(description="Canonical resource ID")],
    provider_address: Annotated[str, Field(description="Provider wallet address")],
    model_id: Annotated[str, Field(description="GPU model ID")],
    tbp_watts: Annotated[int, Field(description="GPU TBP (total board power) in watts")],
    eur_per_kwh: Annotated[float, Field(description="EUR per kWh tariff")],
    wallet: Annotated[str | None, Field(description="Wallet name for signing")],
    wallet_path: Annotated[str | None, Field(description="Direct wallet file path")],
    password: Annotated[str | None, Field(description="Wallet password")],
    password_file: Annotated[str | None, Field(description="Wallet password file")],
    json_output: Annotated[bool | None, Field(description="Output raw JSON")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Register a GPU energy profile on the IEnergyPricing contract.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"json_output": "json-output"},
        values={
            "resource_id": "resource-id",
            "provider_address": "provider-address",
            "model_id": "model-id",
            "tbp_watts": "tbp-watts",
            "eur_per_kwh": "eur-per-kwh",
            "wallet": "wallet",
            "wallet_path": "wallet-path",
            "password": "password",
            "password_file": "password-file",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "energy",
        subcommand=["provider", "register"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "energy",
            subcommand=["provider", "register"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
