# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 4 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_genesis_info(
    chain_id: Annotated[
        str | None, Field(description="Chain ID to show info for (auto-detected from blockchain node if not provided)")
    ],
    data_dir: Annotated[str | None, Field(description="Data directory path (default: /var/lib/aitbc/data)")],
    rpc_url: Annotated[
        str | None, Field(description="Blockchain RPC URL for chain ID auto-detection (default: http://localhost:8202)")
    ],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show the genesis block information for a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if data_dir is not None:
        options["data-dir"] = data_dir
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "genesis",
        subcommand=["info"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_genesis_init(
    chain_id: Annotated[str | None, Field(description="Chain ID for genesis (auto-detected from config if not provided)")],
    create_wallet: Annotated[bool | None, Field(description="Create genesis wallet with secure random key")],
    password: Annotated[str | None, Field(description="Wallet password (auto-generated if not provided)")],
    proposer: Annotated[str | None, Field(description="Proposer address (defaults to genesis wallet)")],
    force: Annotated[bool | None, Field(description="Force overwrite existing genesis")],
    register_service: Annotated[bool | None, Field(description="Register genesis wallet with wallet service")],
    service_url: Annotated[str | None, Field(description="Wallet service URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Initialize the genesis configuration and files for the local chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if create_wallet:
        options["create-wallet"] = None
    if password is not None:
        options["password"] = password
    if proposer is not None:
        options["proposer"] = proposer
    if force:
        options["force"] = None
    if register_service:
        options["register-service"] = None
    if service_url is not None:
        options["service-url"] = service_url
    args = None
    command = _build_aitbc_cli_command(
        "genesis",
        subcommand=["init"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "genesis",
            subcommand=["init"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_genesis_sync_from_hub(
    chain_id: Annotated[
        str | None, Field(description="Chain ID to sync genesis for (auto-detected from config if not provided)")
    ],
    rpc_url: Annotated[str | None, Field(description="Hub RPC URL to fetch genesis from (default: from config)")],
    data_dir: Annotated[str | None, Field(description="Data directory path (default: /var/lib/aitbc/data)")],
    force: Annotated[bool | None, Field(description="Force overwrite existing genesis.json")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Sync the genesis block from the hub for a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if rpc_url is not None:
        options["rpc-url"] = rpc_url
    if data_dir is not None:
        options["data-dir"] = data_dir
    if force:
        options["force"] = None
    args = None
    command = _build_aitbc_cli_command(
        "genesis",
        subcommand=["sync-from-hub"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "genesis",
            subcommand=["sync-from-hub"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_genesis_verify(
    chain_id: Annotated[str | None, Field(description="Chain ID to verify (auto-detected from config if not provided)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Verify the genesis block and configuration for a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "genesis",
        subcommand=["verify"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "genesis",
            subcommand=["verify"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
