# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 20 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from decimal import Decimal

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_chains(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List chains that participate in inter-chain trading.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["chains"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["chains"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_create(
    source_chain: Annotated[str, Field(description="Source chain ID")],
    dest_chain: Annotated[str, Field(description="Destination chain ID")],
    sender: Annotated[str, Field(description="Sender address (source chain)")],
    recipient: Annotated[str, Field(description="Recipient address (dest chain)")],
    amount: Annotated[int, Field(description="Amount to trade")],
    offer_id: Annotated[str | None, Field(description="Associated offer ID")],
    price: Annotated[Decimal | None, Field(description="Trade price")],
    quantity: Annotated[int | None, Field(description="Trade quantity")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create a new inter-chain trade between source and destination chains.."""
    options: dict[str, Any] = {}
    if source_chain is not None:
        options["source-chain"] = source_chain
    if dest_chain is not None:
        options["dest-chain"] = dest_chain
    if sender is not None:
        options["sender"] = sender
    if recipient is not None:
        options["recipient"] = recipient
    if amount is not None:
        options["amount"] = amount
    if offer_id is not None:
        options["offer-id"] = offer_id
    if price is not None:
        options["price"] = price
    if quantity is not None:
        options["quantity"] = quantity
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["create"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["create"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_discover(
    source_chain: Annotated[str | None, Field(description="Filter by source chain")],
    dest_chain: Annotated[str | None, Field(description="Filter by destination chain")],
    service_type: Annotated[str | None, Field(description="Filter by service type (e.g. gpu_marketplace)")],
    min_price: Annotated[Decimal | None, Field(description="Minimum price filter")],
    max_price: Annotated[Decimal | None, Field(description="Maximum price filter")],
    region: Annotated[str | None, Field(description="Filter by region")],
    gpu_model: Annotated[str | None, Field(description="Filter by GPU model")],
    limit: Annotated[int | None, Field(description="Max results")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Discover trading offers across chains with optional filters.."""
    options: dict[str, Any] = {}
    if source_chain is not None:
        options["source-chain"] = source_chain
    if dest_chain is not None:
        options["dest-chain"] = dest_chain
    if service_type is not None:
        options["service-type"] = service_type
    if min_price is not None:
        options["min-price"] = min_price
    if max_price is not None:
        options["max-price"] = max_price
    if region is not None:
        options["region"] = region
    if gpu_model is not None:
        options["gpu-model"] = gpu_model
    if limit is not None:
        options["limit"] = limit
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["discover"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["discover"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_get(
    trade_id: Annotated[str, Field(description="Positional argument: trade_id")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get details of a specific trade.."""
    options: dict[str, Any] = {}
    args = [trade_id] if trade_id is not None else []
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["get"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["get"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_health(
    chain_id: Annotated[str, Field(description="Chain ID to check")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Check the health of inter-chain trading for a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["health"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["health"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_history(
    source_chain: Annotated[str | None, Field(description="Filter by source chain")],
    dest_chain: Annotated[str | None, Field(description="Filter by destination chain")],
    limit: Annotated[int | None, Field(description="Max results")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Show the history of inter-chain trades between source and destination chains.."""
    options: dict[str, Any] = {}
    if source_chain is not None:
        options["source-chain"] = source_chain
    if dest_chain is not None:
        options["dest-chain"] = dest_chain
    if limit is not None:
        options["limit"] = limit
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["history"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["history"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_list(
    status: Annotated[str | None, Field(description="Filter by status (pending, matched, completed, etc.)")],
    source_chain: Annotated[str | None, Field(description="Filter by source chain")],
    dest_chain: Annotated[str | None, Field(description="Filter by destination chain")],
    limit: Annotated[int | None, Field(description="Max results")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List inter-chain trades with optional filters.."""
    options: dict[str, Any] = {}
    if status is not None:
        options["status"] = status
    if source_chain is not None:
        options["source-chain"] = source_chain
    if dest_chain is not None:
        options["dest-chain"] = dest_chain
    if limit is not None:
        options["limit"] = limit
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["list"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["list"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_lock_escrow(
    trade_id: Annotated[str, Field(description="Trade ID to lock escrow for")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    timeout_opt: Annotated[int | None, Field(description="Escrow timeout in seconds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Lock escrow for a trade on the settlement node.."""
    options: dict[str, Any] = {}
    if trade_id is not None:
        options["trade-id"] = trade_id
    if node_url is not None:
        options["node-url"] = node_url
    if timeout_opt is not None:
        options["timeout"] = timeout_opt
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["lock-escrow"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["lock-escrow"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_match(
    trade_id: Annotated[str, Field(description="Positional argument: trade_id")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Match a trade with a counterparty or settlement path.."""
    options: dict[str, Any] = {}
    args = [trade_id] if trade_id is not None else []
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["match"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["match"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_match_all(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Match all open inter-chain trades automatically.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["match-all"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["match-all"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_refund(
    trade_id: Annotated[str, Field(description="Trade ID to refund")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Refund a trade on the settlement node.."""
    options: dict[str, Any] = {}
    if trade_id is not None:
        options["trade-id"] = trade_id
    if node_url is not None:
        options["node-url"] = node_url
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["refund"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["refund"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_register_chain(
    chain_id: Annotated[str, Field(description="Chain ID to register")],
    endpoint: Annotated[str, Field(description="Blockchain node RPC URL for the chain")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Register a new chain for inter-chain trading.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if endpoint is not None:
        options["endpoint"] = endpoint
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["register-chain"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["register-chain"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_search(
    query: Annotated[str | None, Field(description="Search query text")],
    chain_id: Annotated[str | None, Field(description="Filter by chain ID")],
    service_type: Annotated[str | None, Field(description="Filter by service type")],
    min_price: Annotated[Decimal | None, Field(description="Minimum price filter")],
    max_price: Annotated[Decimal | None, Field(description="Maximum price filter")],
    limit: Annotated[int | None, Field(description="Max results")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Search trading offers with a query.."""
    options: dict[str, Any] = {}
    if query is not None:
        options["query"] = query
    if chain_id is not None:
        options["chain-id"] = chain_id
    if service_type is not None:
        options["service-type"] = service_type
    if min_price is not None:
        options["min-price"] = min_price
    if max_price is not None:
        options["max-price"] = max_price
    if limit is not None:
        options["limit"] = limit
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["search"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["search"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_settle(
    trade_id: Annotated[str, Field(description="Trade ID to settle")],
    secret: Annotated[str, Field(description="HTLC secret to reveal")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Settle a trade with a secret.."""
    options: dict[str, Any] = {}
    if trade_id is not None:
        options["trade-id"] = trade_id
    if secret is not None:
        options["secret"] = secret
    if node_url is not None:
        options["node-url"] = node_url
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["settle"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["settle"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_settlement_status(
    trade_id: Annotated[str, Field(description="Trade ID to check")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get the settlement status of a trade.."""
    options: dict[str, Any] = {}
    if trade_id is not None:
        options["trade-id"] = trade_id
    if node_url is not None:
        options["node-url"] = node_url
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["settlement-status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["settlement-status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_status(
    trade_id: Annotated[str, Field(description="Trade ID")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get the status of a specific trade.."""
    options: dict[str, Any] = {}
    if trade_id is not None:
        options["trade-id"] = trade_id
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_subscription_status(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Show the subscription status for trading updates.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["subscription-status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["subscription-status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_sync(
    chain_id: Annotated[str | None, Field(description="Sync specific chain (default: all chains)")],
    service_type: Annotated[str | None, Field(description="Sync specific service type")],
    force: Annotated[bool | None, Field(description="Force sync even if offers are fresh")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Sync trading data for a chain and service type.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if service_type is not None:
        options["service-type"] = service_type
    if force:
        options["force"] = None
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["sync"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["sync"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_sync_status(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get the inter-chain trading sync status.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["sync-status"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["sync-status"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_trade_watch(
    chain_id: Annotated[str | None, Field(description="Filter by chain ID")],
    service_type: Annotated[str | None, Field(description="Filter by service type")],
    min_price: Annotated[Decimal | None, Field(description="Minimum price filter")],
    max_price: Annotated[Decimal | None, Field(description="Maximum price filter")],
    region: Annotated[str | None, Field(description="Filter by region")],
    gpu_model: Annotated[str | None, Field(description="Filter by GPU model")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Watch for new trading offers matching filters.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if service_type is not None:
        options["service-type"] = service_type
    if min_price is not None:
        options["min-price"] = min_price
    if max_price is not None:
        options["max-price"] = max_price
    if region is not None:
        options["region"] = region
    if gpu_model is not None:
        options["gpu-model"] = gpu_model
    args = None
    command = _build_aitbc_cli_command(
        "trade",
        subcommand=["watch"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "trade",
            subcommand=["watch"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
