# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 1 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_http_call(
    service: Annotated[str, Field(description="Positional argument: service")],
    path: Annotated[str, Field(description="Positional argument: path")],
    method: Annotated[str | None, Field(description="HTTP method (GET, POST, PUT, PATCH, DELETE)")],
    params: Annotated[str | None, Field(description="JSON object of query parameters")],
    body: Annotated[str | None, Field(description="JSON object request body")],
    url: Annotated[str | None, Field(description="Override the service base URL")],
    api_key: Annotated[str | None, Field(description="API key (X-API-Key) header")],
    auth_kind: Annotated[Literal["none", "miner"] | None, Field(description="Use configured API key for auth")],
    timeout_opt: Annotated[int | None, Field(description="Request timeout in seconds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Call an AITBC HTTP endpoint by service name and path.."""
    options: dict[str, Any] = {}
    if method is not None:
        options["method"] = method
    if params is not None:
        options["params"] = params
    if body is not None:
        options["body"] = body
    if url is not None:
        options["url"] = url
    if api_key is not None:
        options["api-key"] = api_key
    if auth_kind is not None:
        options["auth"] = auth_kind
    if timeout_opt is not None:
        options["timeout"] = timeout_opt
    args = [] + ([service] if service is not None else []) + ([path] if path is not None else [])
    command = _build_aitbc_cli_command(
        "http",
        subcommand=["call"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "http",
            subcommand=["call"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
