# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 2 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_reinvest_policy(
    agent_id: Annotated[str, Field(description="The Agent-id.")],
    staking_pct: Annotated[str | None, Field(description="Percentage directed to staking")],
    reserve_pct: Annotated[str | None, Field(description="Percentage kept in reserve")],
    min_reinvest: Annotated[str | None, Field(description="Minimum amount to reinvest")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Show or record a reinvestment policy for an agent.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    if staking_pct is not None:
        options["staking-pct"] = staking_pct
    if reserve_pct is not None:
        options["reserve-pct"] = reserve_pct
    if min_reinvest is not None:
        options["min-reinvest"] = min_reinvest
    args = None
    command = _build_aitbc_cli_command(
        "reinvest",
        subcommand=["policy"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "reinvest",
            subcommand=["policy"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_reinvest_simulate(
    agent_id: Annotated[str, Field(description="The Agent-id.")],
    earnings: Annotated[str | None, Field(description="Earnings amount to simulate")],
    budget_total: Annotated[str | None, Field(description="Total budget for the agent")],
    staking_contract: Annotated[str | None, Field(description="Staking contract address")],
    reserve_address: Annotated[str | None, Field(description="Reserve address for capacity funds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Simulate reinvestment actions for a given earnings amount.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    if earnings is not None:
        options["earnings"] = earnings
    if budget_total is not None:
        options["budget-total"] = budget_total
    if staking_contract is not None:
        options["staking-contract"] = staking_contract
    if reserve_address is not None:
        options["reserve-address"] = reserve_address
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "reinvest",
        subcommand=["simulate"],
        args=args,
        options=options,
        timeout=timeout,
    )
