# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 10 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_comm_collaborate(
    agent_ids: Annotated[list[str], Field(description="The Agent ids.")],
    collaboration_type: Annotated[str, Field(description="The Collaboration type.")],
    governance: Annotated[str | None, Field(description="Governance rules (JSON string)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Create a multi-agent collaboration with a list of agent IDs.."""
    options: dict[str, Any] = {}
    if agent_ids is not None:
        options["agent-ids"] = agent_ids
    if collaboration_type is not None:
        options["collaboration-type"] = collaboration_type
    if governance is not None:
        options["governance"] = governance
    args = None
    command = _build_aitbc_cli_command(
        "agent-comm",
        subcommand=["collaborate"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-comm",
            subcommand=["collaborate"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_comm_discover(
    chain_id: Annotated[str, Field(description="The Chain id.")],
    capabilities: Annotated[str | None, Field(description="Required capabilities (comma-separated)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Discover active agents on a specific chain by chain ID.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if capabilities is not None:
        options["capabilities"] = capabilities
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-comm",
        subcommand=["discover"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_comm_list(
    chain_id: Annotated[str | None, Field(description="Filter by chain ID")],
    status: Annotated[Literal["active", "inactive", "busy", "offline"] | None, Field(description="Filter by status")],
    capabilities: Annotated[str | None, Field(description="Filter by capabilities (comma-separated)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List agents registered in the cross-chain network with optional filters.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    if status is not None:
        options["status"] = status
    if capabilities is not None:
        options["capabilities"] = capabilities
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-comm",
        subcommand=["list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_comm_monitor(
    realtime: Annotated[bool | None, Field(description="Real-time monitoring")],
    interval: Annotated[int | None, Field(description="Update interval in seconds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Monitor cross-chain agent communication in real time or at an interval.."""
    options: dict[str, Any] = {}
    if realtime:
        options["realtime"] = None
    if interval is not None:
        options["interval"] = interval
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-comm",
        subcommand=["monitor"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_comm_network(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get an overview of the cross-chain agent network and distribution.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-comm",
        subcommand=["network"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_comm_receive(
    receiver_id: Annotated[str, Field(description="The Receiver id.")],
    limit: Annotated[int | None, Field(description="Maximum number of messages to return")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Receive queued messages for a receiver agent from the coordinator.."""
    options: dict[str, Any] = {}
    if receiver_id is not None:
        options["receiver-id"] = receiver_id
    if limit is not None:
        options["limit"] = limit
    args = None
    command = _build_aitbc_cli_command(
        "agent-comm",
        subcommand=["receive"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-comm",
            subcommand=["receive"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_comm_register(
    agent_id: Annotated[str, Field(description="The Agent id.")],
    name: Annotated[str, Field(description="Wallet name.")],
    chain_id: Annotated[str, Field(description="The Chain id.")],
    endpoint: Annotated[str, Field(description="The Endpoint.")],
    capabilities: Annotated[str | None, Field(description="Comma-separated list of capabilities")],
    reputation: Annotated[float | None, Field(description="Initial reputation score")],
    version: Annotated[str | None, Field(description="Agent version")],
    agent_type: Annotated[str | None, Field(description="Agent type (worker, specialist, etc.)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Register a new agent in the cross-chain network with its metadata and endpoint.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    if name is not None:
        options["name"] = name
    if chain_id is not None:
        options["chain-id"] = chain_id
    if endpoint is not None:
        options["endpoint"] = endpoint
    if capabilities is not None:
        options["capabilities"] = capabilities
    if reputation is not None:
        options["reputation"] = reputation
    if version is not None:
        options["version"] = version
    if agent_type is not None:
        options["agent-type"] = agent_type
    args = None
    command = _build_aitbc_cli_command(
        "agent-comm",
        subcommand=["register"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-comm",
            subcommand=["register"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_comm_reputation(
    agent_id: Annotated[str, Field(description="The Agent id.")],
    interaction_result: Annotated[Literal["success", "failure"], Field(description="The Interaction result.")],
    feedback: Annotated[float | None, Field(description="Feedback score (0.0-1.0)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Update the reputation score for an agent based on an interaction result.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    if interaction_result is not None:
        options["interaction-result"] = interaction_result
    if feedback is not None:
        options["feedback"] = feedback
    args = None
    command = _build_aitbc_cli_command(
        "agent-comm",
        subcommand=["reputation"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-comm",
            subcommand=["reputation"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_agent_comm_send(
    sender_id: Annotated[str, Field(description="The Sender id.")],
    receiver_id: Annotated[str, Field(description="The Receiver id.")],
    message_type: Annotated[str, Field(description="The Message type.")],
    chain_id: Annotated[str, Field(description="The Chain id.")],
    payload: Annotated[str | None, Field(description="JSON payload string")],
    target_chain: Annotated[str | None, Field(description="Target chain for cross-chain messages")],
    priority: Annotated[int | None, Field(description="Message priority (1-10)")],
    ttl: Annotated[int | None, Field(description="Time to live in seconds")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Send a message from a sender to a receiver agent on a specific chain.."""
    options: dict[str, Any] = {}
    if sender_id is not None:
        options["sender-id"] = sender_id
    if receiver_id is not None:
        options["receiver-id"] = receiver_id
    if message_type is not None:
        options["message-type"] = message_type
    if chain_id is not None:
        options["chain-id"] = chain_id
    if payload is not None:
        options["payload"] = payload
    if target_chain is not None:
        options["target-chain"] = target_chain
    if priority is not None:
        options["priority"] = priority
    if ttl is not None:
        options["ttl"] = ttl
    args = None
    command = _build_aitbc_cli_command(
        "agent-comm",
        subcommand=["send"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "agent-comm",
            subcommand=["send"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_agent_comm_status(
    agent_id: Annotated[str, Field(description="The Agent id.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get detailed status and metadata for a registered agent.."""
    options: dict[str, Any] = {}
    if agent_id is not None:
        options["agent-id"] = agent_id
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "agent-comm",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )
