# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 10 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_activity_timeline(
    period: Annotated[str | None, Field(description="Time period (1h, 24h, 7d, 30d)")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get the daily transaction activity timeline for a period.."""
    options: dict[str, Any] = {}
    if period is not None:
        options["period"] = period
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["activity-timeline"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["activity-timeline"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_block_by_hash(
    block_hash: Annotated[str, Field(description="The Block hash.")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get a block by its hash on the specified chain.."""
    options: dict[str, Any] = {}
    if block_hash is not None:
        options["block-hash"] = block_hash
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["block-by-hash"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["block-by-hash"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_blocks_by_address(
    address: Annotated[str, Field(description="Blockchain address to fund.")],
    limit: Annotated[int | None, Field(description="Number of blocks to return")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get blocks containing transactions for a given address.."""
    options: dict[str, Any] = {}
    if address is not None:
        options["address"] = address
    if limit is not None:
        options["limit"] = limit
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["blocks-by-address"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["blocks-by-address"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_chains(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List all supported chains and their basic configuration.."""
    options: dict[str, Any] = {}
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["chains"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["chains"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_network_stats(
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get network-wide statistics for a chain.."""
    options: dict[str, Any] = {}
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["network-stats"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["network-stats"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_non_empty_blocks(
    limit: Annotated[int | None, Field(description="Number of blocks to return")],
    offset: Annotated[int | None, Field(description="Offset for pagination")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List non-empty blocks with optional limit, offset, and chain filters.."""
    options: dict[str, Any] = {}
    if limit is not None:
        options["limit"] = limit
    if offset is not None:
        options["offset"] = offset
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["non-empty-blocks"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["non-empty-blocks"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_provider_reputation(
    provider_id: Annotated[str, Field(description="The Provider id.")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get reputation information for a provider by ID.."""
    options: dict[str, Any] = {}
    if provider_id is not None:
        options["provider-id"] = provider_id
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["provider-reputation"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["provider-reputation"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_search_transactions(
    address: Annotated[str, Field(description="Blockchain address to fund.")],
    limit: Annotated[int | None, Field(description="Number of transactions to return")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Search transactions for an address with a result limit.."""
    options: dict[str, Any] = {}
    if address is not None:
        options["address"] = address
    if limit is not None:
        options["limit"] = limit
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["search-transactions"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["search-transactions"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_top_addresses(
    limit: Annotated[int | None, Field(description="Number of addresses to return")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List the top addresses by balance on a chain.."""
    options: dict[str, Any] = {}
    if limit is not None:
        options["limit"] = limit
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["top-addresses"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["top-addresses"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_explorer_transaction_by_hash(
    tx_hash: Annotated[str, Field(description="The Tx hash.")],
    chain_id: Annotated[str | None, Field(description="Chain ID to query")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Get full transaction details by its hash.."""
    options: dict[str, Any] = {}
    if tx_hash is not None:
        options["tx-hash"] = tx_hash
    if chain_id is not None:
        options["chain-id"] = chain_id
    args = None
    command = _build_aitbc_cli_command(
        "explorer",
        subcommand=["transaction-by-hash"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "explorer",
            subcommand=["transaction-by-hash"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
