# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 14 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any, Literal

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _collect_options,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_active(
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List every dispute still open for arbitration.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["active"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["active"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_arbitrator_authorize(
    arbitrator_address: Annotated[str, Field(description="Positional argument: arbitrator_address")],
    revoke: Annotated[bool | None, Field(description="Revoke authorization instead of granting it.")],
    owner_signature: Annotated[
        str | None, Field(description="Owner signature authorising the change; required by nodes that enforce it.")
    ],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Grant or revoke arbitrator rights for an address (admin only).."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"revoke": "revoke"},
        values={"owner_signature": "signature", "node_url": "node-url"},
    )
    args = [arbitrator_address] if arbitrator_address is not None else []
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["arbitrator", "authorize"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["arbitrator", "authorize"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_dispute_arbitrator_list(
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List every authorized arbitrator.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "dispute",
        subcommand=["arbitrator", "list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_arbitrator_queue(
    arbitrator_address: Annotated[str, Field(description="Positional argument: arbitrator_address")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List the disputes assigned to an arbitrator.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = [arbitrator_address] if arbitrator_address is not None else []
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["arbitrator", "queue"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["arbitrator", "queue"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_auto_adjudicate(
    assume_yes: Annotated[bool | None, Field(description="Skip the confirmation prompt.")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Auto-resolve every dispute whose spot-check evidence proves a mismatch (S-3).."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"assume_yes": "yes"},
        values={"coordinator_url": "coordinator-url"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["auto-adjudicate"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["auto-adjudicate"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_evidence_add(
    dispute_id: Annotated[int, Field(description="Dispute the evidence belongs to.")],
    evidence_hash: Annotated[str, Field(description="Content hash of the evidence.")],
    evidence_type: Annotated[str, Field(description="Evidence category, e.g. transcript or receipt.")],
    description: Annotated[str, Field(description="What the evidence shows.")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Submit evidence for a dispute.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={
            "dispute_id": "dispute-id",
            "evidence_hash": "evidence-hash",
            "evidence_type": "evidence-type",
            "description": "description",
            "node_url": "node-url",
        },
    )
    args = None
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["evidence", "add"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["evidence", "add"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_dispute_evidence_list(
    dispute_id: Annotated[str, Field(description="Positional argument: dispute_id")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List the evidence submitted for a dispute.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = [dispute_id] if dispute_id is not None else []
    return _aitbc_cli_read_tool(
        role,
        host,
        "dispute",
        subcommand=["evidence", "list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_evidence_verify(
    dispute_id: Annotated[int, Field(description="Dispute the evidence belongs to.")],
    evidence_id: Annotated[int, Field(description="Evidence entry to rule on.")],
    reject: Annotated[bool | None, Field(description="Mark the evidence as not verified instead of verified.")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Verify or reject a piece of evidence (arbitrators only).."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"reject": "reject"},
        values={"dispute_id": "dispute-id", "evidence_id": "evidence-id", "node_url": "node-url"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["evidence", "verify"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["evidence", "verify"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_dispute_file(
    agreement_id: Annotated[int, Field(description="Agreement the dispute is raised against.")],
    respondent: Annotated[str, Field(description="Address of the party the dispute is filed against.")],
    dispute_type: Annotated[str, Field(description="Dispute category, e.g. non_delivery or quality.")],
    reason: Annotated[str, Field(description="Why the dispute is being filed.")],
    evidence_hash: Annotated[str, Field(description="Hash of the supporting evidence.")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """File a new dispute against an agreement.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={
            "agreement_id": "agreement-id",
            "respondent": "respondent",
            "dispute_type": "dispute-type",
            "reason": "reason",
            "evidence_hash": "evidence-hash",
            "node_url": "node-url",
        },
    )
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "dispute",
        subcommand=["file"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_dispute_get(
    dispute_id: Annotated[str, Field(description="Positional argument: dispute_id")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show one dispute with its evidence and votes.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = [dispute_id] if dispute_id is not None else []
    return _aitbc_cli_read_tool(
        role,
        host,
        "dispute",
        subcommand=["get"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_resolve(
    job_id: Annotated[str, Field(description="Positional argument: job_id")],
    outcome: Annotated[
        Literal["refund", "release"],
        Field(description="Whether the escrow returns to the buyer (refund) or pays the provider (release)."),
    ],
    reason: Annotated[str, Field(description="The ruling, recorded on the settlement (1-500 characters).")],
    assume_yes: Annotated[bool | None, Field(description="Skip the confirmation prompt.")],
    coordinator_url: Annotated[str | None, Field(description="Coordinator URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Rule on a disputed job payment (operator or arbiter only).."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={"assume_yes": "yes"},
        values={"outcome": "outcome", "reason": "reason", "coordinator_url": "coordinator-url"},
    )
    args = [job_id] if job_id is not None else []
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["resolve"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["resolve"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_user(
    user_address: Annotated[str, Field(description="Positional argument: user_address")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """List the disputes an address is party to.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = [user_address] if user_address is not None else []
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["user"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["user"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_dispute_vote(
    dispute_id: Annotated[int, Field(description="Dispute being voted on.")],
    vote: Annotated[Literal["plaintiff", "defendant"], Field(description="Which side the vote favours.")],
    reasoning: Annotated[str, Field(description="Why the arbitrator ruled this way; recorded with the vote.")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Cast an arbitration vote on a dispute (arbitrators only).."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"dispute_id": "dispute-id", "vote": "vote", "reasoning": "reasoning", "node_url": "node-url"},
    )
    args = None
    command = _build_aitbc_cli_command(
        "dispute",
        subcommand=["vote"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "dispute",
            subcommand=["vote"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_dispute_votes(
    dispute_id: Annotated[str, Field(description="Positional argument: dispute_id")],
    node_url: Annotated[str | None, Field(description="Blockchain node RPC URL")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Show the arbitration votes cast on a dispute.."""
    options: dict[str, Any] = _collect_options(
        locals(),
        flags={},
        values={"node_url": "node-url"},
    )
    args = [dispute_id] if dispute_id is not None else []
    return _aitbc_cli_read_tool(
        role,
        host,
        "dispute",
        subcommand=["votes"],
        args=args,
        options=options,
        timeout=timeout,
    )
