# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 4 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _aitbc_cli_read_tool,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_workflow_list(
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """List all available workflows from the coordinator.."""
    options: dict[str, Any] = {}
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "workflow",
        subcommand=["list"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_workflow_run(
    workflow_name: Annotated[str, Field(description="The Workflow name.")],
    config: Annotated[str | None, Field(description="Workflow configuration file")],
    dry_run_opt: Annotated[bool | None, Field(description="Dry run without executing")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Run a workflow by name with optional configuration.."""
    options: dict[str, Any] = {}
    if workflow_name is not None:
        options["workflow-name"] = workflow_name
    if config is not None:
        options["config"] = config
    if dry_run_opt:
        options["dry-run"] = None
    args = None
    command = _build_aitbc_cli_command(
        "workflow",
        subcommand=["run"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "workflow",
            subcommand=["run"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )


@mcp.tool(annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False))
def aitbc_workflow_status(
    workflow_name: Annotated[str, Field(description="The Workflow name.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
) -> str:
    """Get the execution status of a workflow by name.."""
    options: dict[str, Any] = {}
    if workflow_name is not None:
        options["workflow-name"] = workflow_name
    args = None
    return _aitbc_cli_read_tool(
        role,
        host,
        "workflow",
        subcommand=["status"],
        args=args,
        options=options,
        timeout=timeout,
    )


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_workflow_stop(
    workflow_name: Annotated[str, Field(description="The Workflow name.")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Stop a running workflow by its execution ID.."""
    options: dict[str, Any] = {}
    if workflow_name is not None:
        options["workflow-name"] = workflow_name
    args = None
    command = _build_aitbc_cli_command(
        "workflow",
        subcommand=["stop"],
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "workflow",
            subcommand=["stop"],
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
