# ---------------------------------------------------------------------------
# Auto-generated AITBC CLI MCP wrappers (all mode, 1 tools)
# Generated by: scripts/dev/generate_mcp_cli_tools.py
# Do not edit manually; regenerate instead.
# ---------------------------------------------------------------------------

from __future__ import annotations

from typing import Annotated, Any

from mcp.types import ToolAnnotations
from pydantic import Field

from aitbc_mcp_server import (
    NodeRole,
    _build_aitbc_cli_command,
    _build_dry_run,
    _host_for_role,
    _json,
    _run_aitbc_cli,
    mcp,
)


@mcp.tool(annotations=ToolAnnotations(destructive_hint=True, open_world_hint=False))
def aitbc_update(
    remote: Annotated[str | None, Field(description="Git remote to pull from (default: origin)")],
    branch: Annotated[str | None, Field(description="Branch to update to (default: main)")],
    role: Annotated[NodeRole | None, Field(description="Node role to query.")] = None,
    host: Annotated[str | None, Field(description="Override the host for this call.")] = None,
    timeout: Annotated[int, Field(description="Timeout in seconds.", ge=5, le=600)] = 120,
    dry_run: Annotated[bool, Field(description="Show the command without executing it.")] = True,
    confirm: Annotated[bool, Field(description="Confirm the action.")] = False,
) -> str:
    """Pull the latest code from git and run the deployment update script.."""
    options: dict[str, Any] = {}
    if remote is not None:
        options["remote"] = remote
    if branch is not None:
        options["branch"] = branch
    args = None
    command = _build_aitbc_cli_command(
        "update",
        subcommand=None,
        args=args,
        options=options,
        output_format="json",
    )
    if dry_run:
        return _json(_build_dry_run("Set dry_run=false to execute.", command))
    if not confirm:
        return _json(
            {
                "error": "Confirmation required",
                "command": command,
                "note": "This command may mutate state. Pass dry_run=false and confirm=true to execute.",
            }
        )
    target = _host_for_role(role, host)
    return _json(
        _run_aitbc_cli(
            target,
            "update",
            subcommand=None,
            args=args,
            options=options,
            output_format="json",
            timeout=timeout,
        )
    )
