#!/usr/bin/env python3
"""
Comprehensive Archive Creator
Creates a comprehensive archive of all completed work
"""

import json
from pathlib import Path
from datetime import datetime

def create_comprehensive_archive(scan_file, archive_dir):
    """Create comprehensive archive of all completed work"""
    
    with open(scan_file, 'r') as f:
        scan_results = json.load(f)
    
    archive_path = Path(archive_dir)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    # Create main archive file
    main_archive = archive_path / f"comprehensive_archive_{timestamp}.md"
    
    archive_content = f"""# AITBC Comprehensive Planning Archive

**Archive Created**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Archive ID**: {timestamp}
**Total Files Processed**: {scan_results['total_files_scanned']}
**Files with Completion**: {scan_results['files_with_completion']}
**Total Completion Markers**: {scan_results['total_completion_markers']}

## Archive Summary

### Files with Completion Markers
"""
    
    for category, summary in scan_results['category_summary'].items():
        archive_content += f"""
#### {category.title()}
- **Files**: {summary['total_files']}
- **Completion Markers**: {summary['total_completion_count']}
"""
    
    archive_content += """

### Files Moved to Completed Documentation
"""
    
    for category, summary in scan_results['category_summary'].items():
        archive_content += f"""
#### {category.title()} Documentation
- **Location**: docs/completed/{category}/
- **Files**: {summary['total_files']}
"""
    
    archive_content += """

## Archive Structure

### Completed Documentation
```
docs/completed/
├── infrastructure/ - Infrastructure completed tasks
├── cli/ - CLI completed tasks
├── backend/ - Backend completed tasks
├── security/ - Security completed tasks
├── exchange/ - Exchange completed tasks
├── blockchain/ - Blockchain completed tasks
├── analytics/ - Analytics completed tasks
├── marketplace/ - Marketplace completed tasks
├── maintenance/ - Maintenance completed tasks
└── general/ - General completed tasks
```

### Archive by Category
```
docs/archive/by_category/
├── infrastructure/ - Infrastructure archive files
├── cli/ - CLI archive files
├── backend/ - Backend archive files
├── security/ - Security archive files
├── exchange/ - Exchange archive files
├── blockchain/ - Blockchain archive files
├── analytics/ - Analytics archive files
├── marketplace/ - Marketplace archive files
├── maintenance/ - Maintenance archive files
└── general/ - General archive files
```

## Next Steps

1. **New Milestone Planning**: docs/10_plan is now clean and ready for new content
2. **Reference Completed Work**: Use docs/completed/ for reference
3. **Archive Access**: Use docs/archive/ for historical information
4. **Template Usage**: Use completed documentation as templates

---
*Generated by AITBC Comprehensive Planning Cleanup*
"""
    
    with open(main_archive, 'w') as f:
        f.write(archive_content)
    
    return str(main_archive)

if __name__ == "__main__":
    scan_file = 'comprehensive_scan_results.json'
    archive_dir = '/opt/aitbc/docs/archive'
    
    archive_file = create_comprehensive_archive(scan_file, archive_dir)
    
    print(f"Comprehensive archive created: {archive_file}")
